using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Utils.Parser.Generators.Internal;

/// <summary>
/// Converts a <see cref="G4Grammar"/> AST into a C# source file that constructs
/// the equivalent <c>Utils.Parser.Model.ParserDefinition</c> programmatically —
/// no runtime .g4 parsing required.
/// </summary>
internal static class GrammarEmitter
{
    private const string GrammarSuffix = "Grammar";

    /// <summary>
    /// Emits a complete C# source file for the given grammar.
    /// </summary>
    /// <param name="grammar">The parsed G4 grammar.</param>
    /// <param name="namespaceName">Namespace for the generated class (may be empty).</param>
    /// <param name="className">Class name for the generated partial class.</param>
    /// <param name="sourceFileName">Original .g4 file name, used in the header comment.</param>
    public static string Emit(
        G4Grammar grammar,
        string namespaceName,
        string className,
        string sourceFileName)
    {
        var sb = new StringBuilder();
        string stringSyntaxName = GetStringSyntaxName(grammar.Name);
        string[] syntaxKeywords = GetStringSyntaxKeywords(grammar);
        string[] stringSyntaxNonAlphanumericTokens = GetStringSyntaxNonAlphanumericTokens(grammar);
        string[] stringSyntaxNumberRules = GetStringSyntaxRulesByName(grammar, "NUMBER");
        string[] stringSyntaxStringRules = GetStringSyntaxRulesByName(grammar, "STRING");

        // ── File header ──────────────────────────────────────────────
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Source: {sourceFileName}");
        sb.AppendLine("// This file was generated by Utils.Parser.Generators — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Utils.Parser.Model;");
        sb.AppendLine("using Utils.Parser.Resolution;");
        sb.AppendLine("using Utils.Parser.Runtime;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Grammar compiled from <c>{sourceFileName}</c>. Do not edit — regenerated on build.</summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Utils.Parser.Generators\", \"0.1.0\")]");
        sb.AppendLine($"internal static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Custom <see cref=\"global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute\"/> name associated with this grammar.</summary>");
        sb.AppendLine($"    public const string StringSyntaxName = \"{Escape(stringSyntaxName)}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Lexer keywords that can be highlighted for this grammar string syntax.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxKeywords {{ get; }} = new string[] {{ {JoinStringLiterals(syntaxKeywords)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Exact lexer literals made only of non-alphanumeric characters, suitable for dedicated operator or punctuation highlighting.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxNonAlphanumericTokens {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxNonAlphanumericTokens)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Lexer rule names containing <c>NUMBER</c>, suitable for numeric literal highlighting.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxNumberRules {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxNumberRules)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Lexer rule names containing <c>STRING</c>, suitable for string literal highlighting.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxStringRules {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxStringRules)} }};");
        sb.AppendLine();

        // ── BuildDefinition() ────────────────────────────────────────
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Constructs the <see cref=\"ParserDefinition\"/> for the <c>{grammar.Name}</c>");
        sb.AppendLine("    /// grammar from pre-compiled rule construction code.");
        sb.AppendLine("    /// No .g4 file parsing occurs at runtime.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ParserDefinition BuildDefinition()");
        sb.AppendLine("    {");
        sb.AppendLine("        int _order = 0;");
        sb.AppendLine();

        // ── Emit lexer rules ─────────────────────────────────────────
        if (grammar.LexerRules.Count > 0)
        {
            sb.AppendLine("        // ── Lexer rules (DEFAULT_MODE) ───────────────────────────");
            foreach (var rule in grammar.LexerRules)
                EmitRule(sb, rule);
            sb.AppendLine();
        }

        // ── Emit extra modes ─────────────────────────────────────────
        foreach (var mode in grammar.ExtraModes)
        {
            sb.AppendLine($"        // ── Lexer rules ({mode.Name}) ─────────────────────────────");
            foreach (var rule in mode.Rules)
                EmitRule(sb, rule);
            sb.AppendLine();
        }

        // ── Emit parser rules ────────────────────────────────────────
        if (grammar.ParserRules.Count > 0)
        {
            sb.AppendLine("        // ── Parser rules ────────────────────────────────────────");
            foreach (var rule in grammar.ParserRules)
                EmitRule(sb, rule);
            sb.AppendLine();
        }

        // ── Build modes ──────────────────────────────────────────────
        sb.AppendLine("        // ── Grammar definition ──────────────────────────────────");
        sb.AppendLine("        return RuleResolver.Resolve(new ParserDefinition(");
        sb.AppendLine($"            Name: \"{Escape(grammar.Name)}\",");

        string grammarType = grammar.Kind switch
        {
            G4GrammarKind.Lexer  => "GrammarType.Lexer",
            G4GrammarKind.Parser => "GrammarType.Parser",
            _                    => "GrammarType.Combined"
        };
        sb.AppendLine($"            Type: {grammarType},");
        EmitGrammarOptions(sb, grammar, indent: 3);
        sb.AppendLine("            Actions: new GrammarAction[0],");
        sb.AppendLine("            Imports: new GrammarImport[0],");

        // modes
        sb.Append("            Modes: new LexerMode[]");
        if (grammar.LexerRules.Count == 0 && grammar.ExtraModes.Count == 0)
        {
            sb.AppendLine(" { },");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("            {");
            sb.Append("                new LexerMode(\"DEFAULT_MODE\", new Rule[] {");
            sb.Append(JoinRuleNames(grammar.LexerRules));
            sb.AppendLine(" })");
            foreach (var mode in grammar.ExtraModes)
            {
                sb.Append($",               new LexerMode(\"{Escape(mode.Name)}\", new Rule[] {{");
                sb.Append(JoinRuleNames(mode.Rules));
                sb.AppendLine(" })");
            }
            sb.AppendLine("            },");
        }

        // parserRules
        sb.Append("            ParserRules: new Rule[] {");
        sb.Append(JoinRuleNames(grammar.ParserRules));
        sb.AppendLine(" },");

        // rootRule
        string rootRule = grammar.ParserRules.Count > 0
            ? $"_{Sanitize(grammar.ParserRules[0].Name)}"
            : "null";
        sb.AppendLine($"            RootRule: {rootRule}));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Static Grammar property ──────────────────────────────────
        sb.AppendLine("    /// <summary>Compiled and cached grammar instance.</summary>");
        sb.AppendLine("    public static CompiledGrammar Grammar { get; } = new CompiledGrammar(BuildDefinition());");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Tokenizes input using the generated grammar and annotates literals with the custom grammar string syntax.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<Token> Tokenize([global::System.Diagnostics.CodeAnalysis.StringSyntax(StringSyntaxName, typeof({className}))] string input) => Grammar.Tokenize(input);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Parses input using the generated grammar and annotates literals with the custom grammar string syntax.</summary>");
        sb.AppendLine($"    public static ParseNode Parse([global::System.Diagnostics.CodeAnalysis.StringSyntax(StringSyntaxName, typeof({className}))] string input) => Grammar.Parse(input);");
        sb.AppendLine();

        // ── Build() convenience method ───────────────────────────────
        sb.AppendLine("    /// <summary>Returns the resolved <see cref=\"ParserDefinition\"/>. Equivalent to <see cref=\"BuildDefinition\"/>.</summary>");
        sb.AppendLine("    public static ParserDefinition Build() => BuildDefinition();");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitGrammarOptions(StringBuilder sb, G4Grammar grammar, int indent)
    {
        string pad = new string(' ', indent * 4);

        if (grammar.Options.Count == 0)
        {
            sb.AppendLine($"{pad}Options: null,");
            return;
        }

        sb.AppendLine($"{pad}Options: new GrammarOptions(new Dictionary<string, string>");
        sb.AppendLine($"{pad}{{");

        int optionIndex = 0;
        foreach (var option in grammar.Options.OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            string suffix = optionIndex < grammar.Options.Count - 1 ? "," : "";
            sb.AppendLine($"{pad}    [\"{Escape(option.Key)}\"] = \"{Escape(option.Value)}\"{suffix}");
            optionIndex++;
        }

        sb.AppendLine($"{pad}}}),");
    }

    // ── Rule emission ────────────────────────────────────────────────

    private static void EmitRule(StringBuilder sb, G4Rule rule)
    {
        string varName = $"_{Sanitize(rule.Name)}";
        sb.Append($"        var {varName} = new Rule(");
        sb.Append($"\"{Escape(rule.Name)}\", _order++, {(rule.IsFragment ? "true" : "false")}, ");
        EmitContent(sb, rule.Content, 2);
        sb.AppendLine(");");
    }

    // ── Content emission ─────────────────────────────────────────────

    private static void EmitContent(StringBuilder sb, G4Content content, int indent)
    {
        string pad = new string(' ', indent * 4);

        switch (content)
        {
            case G4Alternation alt:
                EmitAlternation(sb, alt, indent);
                break;

            case G4Sequence seq:
                EmitSequence(sb, seq, indent);
                break;

            case G4Quantifier q:
                sb.Append("new Quantifier(");
                EmitContent(sb, q.Inner, indent);
                sb.Append($", {q.Min}, {(q.Max.HasValue ? q.Max.Value.ToString() : "null")}");
                if (!q.Greedy) sb.Append(", false");
                sb.Append(")");
                break;

            case G4LiteralMatch lit:
                sb.Append($"new LiteralMatch(\"{Escape(lit.Value)}\")");
                break;

            case G4RangeMatch range:
                sb.Append($"new RangeMatch({CharLiteral(range.From)}, {CharLiteral(range.To)})");
                break;

            case G4CharClassMatch cc:
                EmitCharClass(sb, cc);
                break;

            case G4AnyCharMatch:
                sb.Append("new AnyChar()");
                break;

            case G4RuleRef rr:
                sb.Append($"new RuleRef(\"{Escape(rr.RuleName)}\")");
                break;

            case G4Negation neg:
                sb.Append("new Negation(");
                EmitContent(sb, neg.Inner, indent);
                sb.Append(")");
                break;

            case G4LexerCommand cmd:
                EmitLexerCommand(sb, cmd);
                break;

            case G4EmbeddedAction act:
                if (act.IsPredicate)
                    sb.Append($"new ValidatingPredicate(\"{Escape(act.Code)}\")");
                else
                    sb.Append($"new EmbeddedAction(\"{Escape(act.Code)}\", ActionContext.Alternative, ActionPosition.Inline, new LabelRef[0])");
                break;
        }
    }

    private static void EmitAlternation(StringBuilder sb, G4Alternation alt, int indent)
    {
        if (alt.Alternatives.Count == 1 && alt.Alternatives[0].Items.Count == 1)
        {
            // Single-alternative, single-item: emit content directly wrapped in a minimal Alternation
            EmitSingleAltWrap(sb, alt.Alternatives[0], indent);
            return;
        }

        sb.AppendLine("new Alternation(new Alternative[]");
        sb.AppendLine(new string(' ', indent * 4) + "{");

        for (int i = 0; i < alt.Alternatives.Count; i++)
        {
            var alternative = alt.Alternatives[i];
            sb.Append(new string(' ', (indent + 1) * 4));
            EmitAlternative(sb, alternative, indent + 1);
            if (i < alt.Alternatives.Count - 1) sb.AppendLine(",");
            else sb.AppendLine();
        }

        sb.Append(new string(' ', indent * 4) + "})");
    }

    private static void EmitSingleAltWrap(StringBuilder sb, G4Alternative alt, int indent)
    {
        sb.AppendLine("new Alternation(new Alternative[]");
        sb.AppendLine(new string(' ', indent * 4) + "{");
        sb.Append(new string(' ', (indent + 1) * 4));
        EmitAlternative(sb, alt, indent + 1);
        sb.AppendLine();
        sb.Append(new string(' ', indent * 4) + "})");
    }

    private static void EmitAlternative(StringBuilder sb, G4Alternative alt, int indent)
    {
        string pad = new string(' ', indent * 4);
        sb.Append($"new Alternative({alt.Priority}, Associativity.Left, ");

        var items = alt.Items;

        if (items.Count == 0)
        {
            sb.Append("new Sequence(new RuleContent[0])");
        }
        else if (items.Count == 1 && !(items[0] is G4Sequence))
        {
            EmitContent(sb, items[0], indent + 1);
        }
        else
        {
            EmitSequenceFromItems(sb, items, indent + 1);
        }

        sb.Append(")");
    }

    private static void EmitSequence(StringBuilder sb, G4Sequence seq, int indent)
    {
        EmitSequenceFromItems(sb, seq.Items, indent);
    }

    private static void EmitSequenceFromItems(StringBuilder sb, List<G4Content> items, int indent)
    {
        if (items.Count == 1)
        {
            EmitContent(sb, items[0], indent);
            return;
        }

        string pad  = new string(' ', indent * 4);
        string pad1 = new string(' ', (indent + 1) * 4);

        sb.AppendLine("new Sequence(new RuleContent[]");
        sb.AppendLine(pad + "{");

        for (int i = 0; i < items.Count; i++)
        {
            sb.Append(pad1);
            EmitContent(sb, items[i], indent + 1);
            if (i < items.Count - 1) sb.AppendLine(",");
            else sb.AppendLine();
        }

        sb.Append(pad + "})");
    }

    private static void EmitCharClass(StringBuilder sb, G4CharClassMatch cc)
    {
        sb.Append($"new CharSetMatch(new HashSet<char> {{");
        bool first = true;
        foreach (var (lo, hi) in cc.Entries)
        {
            if (hi.HasValue)
            {
                // Range: expand all chars
                for (char c = lo; c <= hi.Value; c++)
                {
                    if (!first) sb.Append(", ");
                    sb.Append(CharLiteral(c));
                    first = false;
                }
            }
            else
            {
                if (!first) sb.Append(", ");
                sb.Append(CharLiteral(lo));
                first = false;
            }
        }
        sb.Append($"}}, {(cc.Negated ? "true" : "false")})");
    }

    private static void EmitLexerCommand(StringBuilder sb, G4LexerCommand cmd)
    {
        string cmdType = cmd.Name.ToLowerInvariant() switch
        {
            "skip"     => "LexerCommandType.Skip",
            "more"     => "LexerCommandType.More",
            "channel"  => "LexerCommandType.Channel",
            "type"     => "LexerCommandType.Type",
            "pushmode" => "LexerCommandType.PushMode",
            "popmode"  => "LexerCommandType.PopMode",
            "mode"     => "LexerCommandType.Mode",
            _          => $"LexerCommandType.Skip /* unknown: {cmd.Name} */"
        };

        string arg = cmd.Arg != null ? $"\"{Escape(cmd.Arg)}\"" : "null";
        sb.Append($"new LexerCommand({cmdType}, {arg})");
    }

    // ── Helpers ──────────────────────────────────────────────────────

    private static string JoinRuleNames(List<G4Rule> rules)
    {
        if (rules.Count == 0) return "";
        var sb = new StringBuilder();
        for (int i = 0; i < rules.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"_{Sanitize(rules[i].Name)}");
        }
        return sb.ToString();
    }

    /// <summary>
    /// Returns the string syntax name exposed for IDE integrations.
    /// </summary>
    /// <param name="grammarName">Declared grammar name.</param>
    /// <returns>The custom syntax name derived from the grammar name.</returns>
    private static string GetStringSyntaxName(string grammarName)
    {
        if (grammarName.EndsWith(GrammarSuffix, StringComparison.Ordinal) && grammarName.Length > GrammarSuffix.Length)
        {
            return grammarName.Substring(0, grammarName.Length - GrammarSuffix.Length);
        }

        return grammarName;
    }

    /// <summary>
    /// Returns keyword lexer rule names whose recognized text matches the rule name case-insensitively.
    /// </summary>
    /// <param name="grammar">Grammar to inspect.</param>
    /// <returns>Sorted keyword names.</returns>
    private static string[] GetStringSyntaxKeywords(G4Grammar grammar)
    {
        var result = new List<string>();

        foreach (var rule in grammar.LexerRules)
        {
            if (TryGetKeywordName(rule, out var keywordName))
            {
                result.Add(keywordName);
            }
        }

        foreach (var mode in grammar.ExtraModes)
        {
            foreach (var rule in mode.Rules)
            {
                if (TryGetKeywordName(rule, out var keywordName))
                {
                    result.Add(keywordName);
                }
            }
        }

        return result
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(keyword => keyword, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    /// <summary>
    /// Returns exact lexer literals composed only of non-alphanumeric characters.
    /// </summary>
    /// <param name="grammar">Grammar to inspect.</param>
    /// <returns>Sorted literal tokens.</returns>
    private static string[] GetStringSyntaxNonAlphanumericTokens(G4Grammar grammar)
    {
        var result = new List<string>();

        foreach (var rule in grammar.LexerRules)
        {
            if (TryGetNonAlphanumericToken(rule, out var token))
            {
                result.Add(token);
            }
        }

        foreach (var mode in grammar.ExtraModes)
        {
            foreach (var rule in mode.Rules)
            {
                if (TryGetNonAlphanumericToken(rule, out var token))
                {
                    result.Add(token);
                }
            }
        }

        return result
            .Distinct(StringComparer.Ordinal)
            .OrderBy(token => token, StringComparer.Ordinal)
            .ToArray();
    }

    /// <summary>
    /// Returns lexer rule names containing the specified marker.
    /// </summary>
    /// <param name="grammar">Grammar to inspect.</param>
    /// <param name="marker">Case-insensitive marker to search in rule names.</param>
    /// <returns>Sorted lexer rule names.</returns>
    private static string[] GetStringSyntaxRulesByName(G4Grammar grammar, string marker)
    {
        var result = new List<string>();

        foreach (var rule in grammar.LexerRules)
        {
            if (RuleNameContains(rule, marker))
            {
                result.Add(rule.Name);
            }
        }

        foreach (var mode in grammar.ExtraModes)
        {
            foreach (var rule in mode.Rules)
            {
                if (RuleNameContains(rule, marker))
                {
                    result.Add(rule.Name);
                }
            }
        }

        return result
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(ruleName => ruleName, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    /// <summary>
    /// Determines whether the lexer rule represents a keyword that exactly matches its rule name, ignoring case.
    /// </summary>
    /// <param name="rule">Rule to inspect.</param>
    /// <param name="keywordName">Resolved keyword name when the rule is a keyword.</param>
    /// <returns><see langword="true"/> when the rule is a string-syntax keyword.</returns>
    private static bool TryGetKeywordName(G4Rule rule, out string keywordName)
    {
        keywordName = string.Empty;

        if (!TryGetExactLexerLiteral(rule, out var literal))
        {
            return false;
        }

        if (!string.Equals(rule.Name, literal, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        keywordName = rule.Name;
        return true;
    }

    /// <summary>
    /// Determines whether the lexer rule resolves to a non-alphanumeric exact literal.
    /// </summary>
    /// <param name="rule">Rule to inspect.</param>
    /// <param name="token">Resolved literal token when the rule qualifies.</param>
    /// <returns><see langword="true"/> when the rule maps to a punctuation or operator token.</returns>
    private static bool TryGetNonAlphanumericToken(G4Rule rule, out string token)
    {
        token = string.Empty;

        if (!TryGetExactLexerLiteral(rule, out var literal) || literal.Length == 0)
        {
            return false;
        }

        if (literal.Any(char.IsLetterOrDigit))
        {
            return false;
        }

        token = literal;
        return true;
    }

    /// <summary>
    /// Attempts to extract an exact literal matched by a lexer rule.
    /// </summary>
    /// <param name="rule">Rule to inspect.</param>
    /// <param name="literal">Resolved literal when extraction succeeds.</param>
    /// <returns><see langword="true"/> when the rule resolves to one exact literal.</returns>
    private static bool TryGetExactLexerLiteral(G4Rule rule, out string literal)
    {
        literal = string.Empty;

        if (rule.IsFragment)
        {
            return false;
        }

        return TryGetCaseInsensitiveLiteral(rule.Content, out literal);
    }

    /// <summary>
    /// Determines whether the rule name contains the requested marker.
    /// </summary>
    /// <param name="rule">Rule to inspect.</param>
    /// <param name="marker">Marker searched in the rule name.</param>
    /// <returns><see langword="true"/> when the marker appears in the rule name.</returns>
    private static bool RuleNameContains(G4Rule rule, string marker)
    {
        if (rule.IsFragment)
        {
            return false;
        }

        return rule.Name.IndexOf(marker, StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>
    /// Attempts to extract a single case-insensitive literal from grammar content.
    /// </summary>
    /// <param name="content">Grammar content to inspect.</param>
    /// <param name="literal">Resolved literal when extraction succeeds.</param>
    /// <returns><see langword="true"/> when the content maps to a single exact literal.</returns>
    private static bool TryGetCaseInsensitiveLiteral(G4Content content, out string literal)
    {
        switch (content)
        {
            case G4Alternation alternation:
                if (alternation.Alternatives.Count == 1)
                {
                    return TryGetCaseInsensitiveLiteral(alternation.Alternatives[0], out literal);
                }

                break;

            case G4Alternative alternative:
                if (alternative.Items.Count == 0)
                {
                    literal = string.Empty;
                    return false;
                }

                var alternativeBuilder = new StringBuilder();
                foreach (var item in alternative.Items)
                {
                    if (!TryGetCaseInsensitiveLiteral(item, out var itemLiteral))
                    {
                        literal = string.Empty;
                        return false;
                    }

                    alternativeBuilder.Append(itemLiteral);
                }

                literal = alternativeBuilder.ToString();
                return true;

            case G4Sequence sequence:
                var sequenceBuilder = new StringBuilder();
                foreach (var item in sequence.Items)
                {
                    if (!TryGetCaseInsensitiveLiteral(item, out var itemLiteral))
                    {
                        literal = string.Empty;
                        return false;
                    }

                    sequenceBuilder.Append(itemLiteral);
                }

                literal = sequenceBuilder.ToString();
                return sequence.Items.Count > 0;

            case G4LiteralMatch literalMatch:
                literal = literalMatch.Value;
                return true;

            case G4CharClassMatch charClassMatch:
                return TryGetCaseInsensitiveCharacter(charClassMatch, out literal);
        }

        literal = string.Empty;
        return false;
    }

    /// <summary>
    /// Attempts to extract a single character from a character class while allowing case variants only.
    /// </summary>
    /// <param name="charClassMatch">Character class to inspect.</param>
    /// <param name="literal">Resolved single-character literal when extraction succeeds.</param>
    /// <returns><see langword="true"/> when the character class maps to one logical character.</returns>
    private static bool TryGetCaseInsensitiveCharacter(G4CharClassMatch charClassMatch, out string literal)
    {
        literal = string.Empty;

        if (charClassMatch.Negated)
        {
            return false;
        }

        var values = new List<char>();
        foreach (var (lo, hi) in charClassMatch.Entries)
        {
            if (hi.HasValue)
            {
                return false;
            }

            values.Add(lo);
        }

        if (values.Count == 0)
        {
            return false;
        }

        char canonical = char.ToUpperInvariant(values[0]);
        if (values.Any(value => char.ToUpperInvariant(value) != canonical))
        {
            return false;
        }

        literal = values[0].ToString();
        return true;
    }

    /// <summary>
    /// Joins string literals for generated C# array initializers.
    /// </summary>
    /// <param name="values">Values to join.</param>
    /// <returns>Comma-separated C# string literals.</returns>
    private static string JoinStringLiterals(IEnumerable<string> values)
    {
        return string.Join(", ", values.Select(value => $"\"{Escape(value)}\""));
    }

    private static string Sanitize(string name)
    {
        // Replace characters invalid in C# identifiers
        var sb = new StringBuilder();
        foreach (char c in name)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        return sb.ToString();
    }

    private static string Escape(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private static string CharLiteral(char c) => c switch
    {
        '\\' => @"'\\'",
        '\'' => @"'\''",
        '\n' => @"'\n'",
        '\r' => @"'\r'",
        '\t' => @"'\t'",
        '\0' => @"'\0'",
        _    => char.IsControl(c)
                    ? $"'\\u{(int)c:X4}'"
                    : $"'{c}'"
    };
}
