using System.Collections.Generic;
using System.Linq;
using System.Text;
using Utils.Parser.Diagnostics.EmbeddedCode;

namespace Utils.Parser.Generators.Internal;

internal static partial class GrammarEmitter
{
    /// <summary>
    /// Collects <c>@lexer::header</c> blocks that can be injected near the top of generated C# output.
    /// </summary>
    /// <param name="grammar">Parsed grammar AST.</param>
    /// <returns>Lexer header actions in grammar order.</returns>
    private static IReadOnlyList<G4GrammarAction> CollectLexerHeaders(G4Grammar grammar)
    {
        return grammar.Actions
            .Where(action => EmbeddedMembersSupport.IsInjectableLexerHeaderAction(grammar, action))
            .ToArray();
    }

    /// <summary>
    /// Emits lexer header blocks verbatim before generated type declarations using lexer-specific markers.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    /// <param name="lexerHeaders">Lexer header blocks to inject.</param>
    /// <param name="grammar">Parsed grammar AST used for transformer context.</param>
    /// <param name="transformer">Parser embedded-code transformer used for lexer headers.</param>
    private static void EmitLexerHeaders(StringBuilder sb, IReadOnlyList<G4GrammarAction> lexerHeaders, G4Grammar grammar, IParserEmbeddedCodeTransformer transformer)
    {
        foreach (var header in lexerHeaders)
        {
            TransformedEmbeddedCode code = TransformEmbeddedCode(transformer, new RawEmbeddedCode(header.RawCode), ParserEmbeddedCodeLocation.LexerHeader, grammar, null);
            sb.AppendLine("// <auto-generated-lexer-header>");
            foreach (string line in SplitEmbeddedCodeLines(code))
            {
                sb.AppendLine(line);
            }

            sb.AppendLine("// </auto-generated-lexer-header>");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Collects <c>@lexer::members</c> blocks that can be injected into the generated execution context.
    /// </summary>
    /// <param name="grammar">Parsed grammar AST.</param>
    /// <returns>Lexer members actions in grammar order.</returns>
    private static IReadOnlyList<G4GrammarAction> CollectLexerMembers(G4Grammar grammar)
    {
        return grammar.Actions
            .Where(action => EmbeddedMembersSupport.IsInjectableLexerMembersAction(grammar, action))
            .ToArray();
    }

    /// <summary>
    /// Emits lexer members blocks verbatim into the generated execution context using lexer-specific markers.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    /// <param name="lexerMembers">Lexer members blocks to inject.</param>
    /// <param name="grammar">Parsed grammar AST used for transformer context.</param>
    /// <param name="transformer">Parser embedded-code transformer used for lexer members.</param>
    private static void EmitLexerMembers(StringBuilder sb, IReadOnlyList<G4GrammarAction> lexerMembers, G4Grammar grammar, IParserEmbeddedCodeTransformer transformer)
    {
        foreach (var members in lexerMembers)
        {
            TransformedEmbeddedCode code = TransformEmbeddedCode(transformer, new RawEmbeddedCode(members.RawCode), ParserEmbeddedCodeLocation.LexerMembers, grammar, null);
            sb.AppendLine("    // <auto-generated-lexer-members>");
            foreach (string line in SplitEmbeddedCodeLines(code))
            {
                sb.AppendLine($"    {line}");
            }

            sb.AppendLine("    // </auto-generated-lexer-members>");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Collects <c>@lexer::footer</c> blocks that can be injected near the end of generated C# output.
    /// </summary>
    /// <param name="grammar">Grammar AST that may contain lexer footer actions.</param>
    /// <returns>Lexer footer actions in grammar order.</returns>
    private static IReadOnlyList<G4GrammarAction> CollectLexerFooters(G4Grammar grammar)
    {
        return grammar.Actions
            .Where(action => EmbeddedMembersSupport.IsInjectableLexerFooterAction(grammar, action))
            .ToArray();
    }

    /// <summary>
    /// Emits lexer footer blocks verbatim after generated type declarations as trailing C# source.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    /// <param name="lexerFooters">Lexer footer blocks to inject.</param>
    /// <param name="grammar">Parsed grammar AST used for transformer context.</param>
    /// <param name="transformer">Parser embedded-code transformer used for lexer footers.</param>
    private static void EmitLexerFooters(StringBuilder sb, IReadOnlyList<G4GrammarAction> lexerFooters, G4Grammar grammar, IParserEmbeddedCodeTransformer transformer)
    {
        foreach (var footer in lexerFooters)
        {
            TransformedEmbeddedCode code = TransformEmbeddedCode(transformer, new RawEmbeddedCode(footer.RawCode), ParserEmbeddedCodeLocation.LexerFooter, grammar, null);
            sb.AppendLine("// <auto-generated-lexer-footer>");
            foreach (string line in SplitEmbeddedCodeLines(code))
            {
                sb.AppendLine(line);
            }

            sb.AppendLine("// </auto-generated-lexer-footer>");
            sb.AppendLine();
        }
    }
}
