using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Utils.Parser.Diagnostics.EmbeddedCode;

namespace Utils.Parser.Generators.Internal;

/// <summary>
/// Converts a <see cref="G4Grammar"/> AST into a C# source file that constructs
/// the equivalent <c>Utils.Parser.Model.ParserDefinition</c> programmatically —
/// no runtime .g4 parsing required.
/// </summary>
internal static partial class GrammarEmitter
{
    private const string GrammarSuffix = "Grammar";

    /// <summary>
    /// Emits a complete C# source file for the given grammar.
    /// </summary>
    /// <param name="grammar">The parsed G4 grammar.</param>
    /// <param name="namespaceName">Namespace for the generated class (may be empty).</param>
    /// <param name="className">Class name for the generated partial class.</param>
    /// <param name="sourceFileName">Original .g4 file name, used in the header comment.</param>
    /// <param name="embeddedCodeTransformer">Optional parser embedded-code transformer.</param>
    public static string Emit(
        G4Grammar grammar,
        string namespaceName,
        string className,
        string sourceFileName,
        IParserEmbeddedCodeTransformer? embeddedCodeTransformer = null)
    {
        embeddedCodeTransformer ??= NoOpParserEmbeddedCodeTransformer.Instance;
        var sb = new StringBuilder();
        string stringSyntaxName = GetStringSyntaxName(grammar.Name);
        string[] syntaxKeywords = GetStringSyntaxKeywords(grammar);
        string[] stringSyntaxNonAlphanumericTokens = GetStringSyntaxNonAlphanumericTokens(grammar);
        string[] stringSyntaxNumberRules = GetStringSyntaxRulesByName(grammar, "NUMBER");
        string[] stringSyntaxStringRules = GetStringSyntaxRulesByName(grammar, "STRING");
        var embeddedHooks = CollectEmbeddedCodeHooks(grammar, embeddedCodeTransformer);
        var lifecycleHooks = CollectLifecycleHooks(grammar, embeddedCodeTransformer);
        var parserHeaders = CollectParserHeaders(grammar);
        var parserMembers = CollectParserMembers(grammar);
        var parserFooters = CollectParserFooters(grammar);

        // ── File header ──────────────────────────────────────────────
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Source: {sourceFileName}");
        sb.AppendLine("// This file was generated by Utils.Parser.Generators — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Utils.Parser.Model;");
        sb.AppendLine("using Utils.Parser.Resolution;");
        sb.AppendLine("using Utils.Parser.Runtime;");
        sb.AppendLine();

        EmitParserHeaders(sb, parserHeaders, grammar, embeddedCodeTransformer);

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Grammar compiled from <c>{sourceFileName}</c>. Do not edit — regenerated on build.</summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Utils.Parser.Generators\", \"0.1.0\")]");
        sb.AppendLine($"internal static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Custom <see cref=\"global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute\"/> name associated with this grammar.</summary>");
        sb.AppendLine($"    public const string StringSyntaxName = \"{Escape(stringSyntaxName)}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Lexer keywords that can be highlighted for this grammar string syntax.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxKeywords {{ get; }} = new string[] {{ {JoinStringLiterals(syntaxKeywords)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Exact lexer literals made only of non-alphanumeric characters, suitable for dedicated operator or punctuation highlighting.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxNonAlphanumericTokens {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxNonAlphanumericTokens)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Lexer rule names containing <c>NUMBER</c>, suitable for numeric literal highlighting.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxNumberRules {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxNumberRules)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Lexer rule names containing <c>STRING</c>, suitable for string literal highlighting.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<string> StringSyntaxStringRules {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxStringRules)} }};");
        sb.AppendLine();

        // ── BuildDefinition() ────────────────────────────────────────
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Constructs the <see cref=\"ParserDefinition\"/> for the <c>{grammar.Name}</c>");
        sb.AppendLine("    /// grammar from pre-compiled rule construction code.");
        sb.AppendLine("    /// No .g4 file parsing occurs at runtime.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ParserDefinition BuildDefinition()");
        sb.AppendLine("    {");
        sb.AppendLine("        int _order = 0;");
        sb.AppendLine();

        // ── Emit lexer rules ─────────────────────────────────────────
        if (grammar.LexerRules.Count > 0)
        {
            sb.AppendLine("        // ── Lexer rules (DEFAULT_MODE) ───────────────────────────");
            foreach (var rule in grammar.LexerRules)
                EmitRule(sb, rule);
            sb.AppendLine();
        }

        // ── Emit extra modes ─────────────────────────────────────────
        foreach (var mode in grammar.ExtraModes)
        {
            sb.AppendLine($"        // ── Lexer rules ({mode.Name}) ─────────────────────────────");
            foreach (var rule in mode.Rules)
                EmitRule(sb, rule);
            sb.AppendLine();
        }

        // ── Emit parser rules ────────────────────────────────────────
        if (grammar.ParserRules.Count > 0)
        {
            sb.AppendLine("        // ── Parser rules ────────────────────────────────────────");
            foreach (var rule in grammar.ParserRules)
                EmitRule(sb, rule);
            sb.AppendLine();
        }

        // ── Build modes ──────────────────────────────────────────────
        sb.AppendLine("        // ── Grammar definition ──────────────────────────────────");
        sb.AppendLine("        return RuleResolver.Resolve(new ParserDefinition(");
        sb.AppendLine($"            Name: \"{Escape(grammar.Name)}\",");

        string grammarType = grammar.Kind switch
        {
            G4GrammarKind.Lexer  => "GrammarType.Lexer",
            G4GrammarKind.Parser => "GrammarType.Parser",
            _                    => "GrammarType.Combined"
        };
        sb.AppendLine($"            Type: {grammarType},");
        EmitGrammarOptions(sb, grammar, indent: 3);
        sb.AppendLine("            Actions: new GrammarAction[0],");
        sb.AppendLine("            Imports: new GrammarImport[0],");

        // modes
        sb.Append("            Modes: new LexerMode[]");
        if (grammar.LexerRules.Count == 0 && grammar.ExtraModes.Count == 0)
        {
            sb.AppendLine(" { },");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("            {");
            sb.Append("                new LexerMode(\"DEFAULT_MODE\", new Rule[] {");
            sb.Append(JoinRuleNames(grammar.LexerRules));
            sb.AppendLine(" })");
            foreach (var mode in grammar.ExtraModes)
            {
                sb.Append($",               new LexerMode(\"{Escape(mode.Name)}\", new Rule[] {{");
                sb.Append(JoinRuleNames(mode.Rules));
                sb.AppendLine(" })");
            }
            sb.AppendLine("            },");
        }

        // parserRules
        sb.Append("            ParserRules: new Rule[] {");
        sb.Append(JoinRuleNames(grammar.ParserRules));
        sb.AppendLine(" },");

        // rootRule
        string rootRule = grammar.ParserRules.Count > 0
            ? $"_{Sanitize(grammar.ParserRules[0].Name)}"
            : "null";
        sb.AppendLine($"            RootRule: {rootRule}));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Static Grammar property ──────────────────────────────────
        sb.AppendLine("    /// <summary>Compiled and cached grammar instance.</summary>");
        sb.AppendLine("    public static CompiledGrammar Grammar { get; } = new CompiledGrammar(Build());");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Tokenizes input using the generated grammar and annotates literals with the custom grammar string syntax.</summary>");
        sb.AppendLine($"    public static IReadOnlyList<Token> Tokenize([global::System.Diagnostics.CodeAnalysis.StringSyntax(StringSyntaxName, typeof({className}))] string input) => Grammar.Tokenize(input);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Parses input using the generated grammar and annotates literals with the custom grammar string syntax.</summary>");
        sb.AppendLine($"    public static ParseNode Parse([global::System.Diagnostics.CodeAnalysis.StringSyntax(StringSyntaxName, typeof({className}))] string input) => Grammar.Parse(input);");
        sb.AppendLine();
        EmitEmbeddedCodeFacade(sb, className);

        // ── Build() convenience method ───────────────────────────────
        sb.AppendLine("    /// <summary>Builds and validates the resolved <see cref=\"ParserDefinition\"/>.</summary>");
        sb.AppendLine("    public static ParserDefinition Build() => RuleResolver.Resolve(BuildDefinition());");

        sb.AppendLine("}");
        sb.AppendLine();
        EmitExecutionContext(sb, embeddedHooks, lifecycleHooks, parserMembers, className, sourceFileName, grammar, embeddedCodeTransformer);
        EmitParserFooters(sb, parserFooters, grammar, embeddedCodeTransformer);

        return sb.ToString();
    }
}
