using System.Text;

namespace Utils.Parser.Generators.Internal;

internal static partial class GrammarEmitter
{

    /// <summary>
    /// Emits explicit rule call-result helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleCallResultHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Attempts to get the retained result for an assignment-labeled successful child call.</summary>");
        sb.AppendLine("    private static bool TryGetLabeledRuleCallResult(ParserRuleLifecycleContext context, string labelName, out global::Utils.Parser.Runtime.ParserRuleCallResult result)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (context.InvocationFrame?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).TryGetAssignment(labelName, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets retained results for a list-labeled child call in successful execution order.</summary>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<global::Utils.Parser.Runtime.ParserRuleCallResult> GetLabeledRuleCallResults(ParserRuleLifecycleContext context, string labelName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (context.InvocationFrame?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).GetList(labelName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get an ordinal named return from an assignment-labeled child result, preserving present-null values.</summary>");
        sb.AppendLine("    private static bool TryGetLabeledRuleCallReturn(ParserRuleLifecycleContext context, string labelName, string returnName, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        if (TryGetLabeledRuleCallResult(context, labelName, out var result)) return result.TryGetReturn(returnName, out value);");
        sb.AppendLine("        value = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a required assignment-labeled child return while preserving present-null values.</summary>");
        sb.AppendLine("    private static object? GetRequiredLabeledRuleCallReturn(ParserRuleLifecycleContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine(@"        if (!TryGetLabeledRuleCallResult(context, labelName, out var result)) throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Assignment label '"" + labelName + ""' is not available in the current rule invocation."");");
        sb.AppendLine("        if (result.TryGetReturn(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Return '"" + returnName + ""' is not available on assignment label '"" + labelName + ""'."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets present ordinal named returns from list-labeled child results in call order; results missing the return are skipped and present-null values are included.</summary>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<object?> GetLabeledRuleCallReturns(ParserRuleLifecycleContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var values = new global::System.Collections.Generic.List<object?>();");
        sb.AppendLine("        foreach (var result in GetLabeledRuleCallResults(context, labelName)) if (result.TryGetReturn(returnName, out object? value)) values.Add(value);");
        sb.AppendLine("        return values.AsReadOnly();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for storing a passive rule-local value on the current invocation frame.</summary>");
        sb.AppendLine("    private void SetRuleLocal(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine("        _frameManager?.Current?.SetLocal(name, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required typed rule-parameter access.</summary>");
        sb.AppendLine("    private T GetRequiredRuleParameter<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string parameterName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null || !frame.TryGetParameter(parameterName, out object? value))");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + parameterName, parameterName, ""Rule parameter '"" + parameterName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        return CastRequiredRuleAttribute<T>(\"$\" + parameterName, \"parameter\", parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required typed rule-local access.</summary>");
        sb.AppendLine("    private T GetRequiredRuleLocal<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string localName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(localName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null || !frame.TryGetLocal(localName, out object? value))");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        return CastRequiredRuleAttribute<T>(\"$\" + localName, \"local\", localName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for storing a required typed rule-local value on the current invocation frame.</summary>");
        sb.AppendLine("    private void SetRequiredRuleLocal<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string localName, T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(localName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null)");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        EnsureRequiredRuleLocalPresent(frame, localName);");
        sb.AppendLine("        frame.SetLocal(localName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for assignment-labeled child result access.</summary>");
        sb.AppendLine("    private bool TryGetLabeledRuleCallResult(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, out global::Utils.Parser.Runtime.ParserRuleCallResult result)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (_frameManager?.Current?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).TryGetAssignment(labelName, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for ordered list-labeled child result access.</summary>");
        sb.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<global::Utils.Parser.Runtime.ParserRuleCallResult> GetLabeledRuleCallResults(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (_frameManager?.Current?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).GetList(labelName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for assignment-labeled child return access.</summary>");
        sb.AppendLine("    private bool TryGetLabeledRuleCallReturn(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, string returnName, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        if (TryGetLabeledRuleCallResult(context, labelName, out var result)) return result.TryGetReturn(returnName, out value);");
        sb.AppendLine("        value = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required assignment-labeled child return access.</summary>");
        sb.AppendLine("    private object? GetRequiredLabeledRuleCallReturn(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine(@"        if (!TryGetLabeledRuleCallResult(context, labelName, out var result)) throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Assignment label '"" + labelName + ""' is not available in the current rule invocation."");");
        sb.AppendLine("        if (result.TryGetReturn(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Return '"" + returnName + ""' is not available on assignment label '"" + labelName + ""'."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required current-rule return access.</summary>");
        sb.AppendLine("    private object? GetRequiredRuleReturn(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is not null && frame.TryGetReturnValue(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + context.Rule.Name + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for typed required current-rule return access.</summary>");
        sb.AppendLine("    private T GetRequiredRuleReturn<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (T)GetRequiredRuleReturn(context, returnName)!;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for storing a required typed current-rule return on the active invocation frame.</summary>");
        sb.AppendLine("    private void SetRequiredRuleReturn<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string returnName, T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null)");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + context.Rule.Name + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        EnsureRequiredRuleReturnPresent(frame, returnName, context.Rule.Name);");
        sb.AppendLine("        frame.SetReturnValue(returnName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload returning present list-labeled child returns in call order, skipping absent returns.</summary>");
        sb.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<object?> GetLabeledRuleCallReturns(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var values = new global::System.Collections.Generic.List<object?>();");
        sb.AppendLine("        foreach (var result in GetLabeledRuleCallResults(context, labelName)) if (result.TryGetReturn(returnName, out object? value)) values.Add(value);");
        sb.AppendLine("        return values.AsReadOnly();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the most recent completed child rule call result from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <returns>The last completed child call result, or <c>null</c> when no child rule has yet completed successfully or no frame is available.</returns>");
        sb.AppendLine("    /// <remarks>Returns are not propagated automatically. Limited read-only parser return attributes project the same rollback-safe frame state; no implicit variables are generated.</remarks>");
        sb.AppendLine("    private static global::Utils.Parser.Runtime.ParserRuleCallResult? GetLastRuleCallResult(ParserRuleLifecycleContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame?.LastCompletedChildCall;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get the raw call-site argument text from the most recent completed child rule call result.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; the helper returns <c>false</c> when the last call result is for a different rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Receives the raw call-site argument text when present on the matching result.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result exists and carries non-null raw argument text; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Raw arguments are metadata only: not evaluated, not bound to child parameters. Use <c>SetNextRuleParameter(...)</c> for explicit seeding.</remarks>");
        sb.AppendLine("    private static bool TryGetLastRuleCallRawArguments(ParserRuleLifecycleContext context, string ruleName, out string? rawArguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        var result = context.InvocationFrame?.LastCompletedChildCall;");
        sb.AppendLine("        if (result is null || !string.Equals(result.RuleName, ruleName, global::System.StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.AppendLine("            rawArguments = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        rawArguments = result.RawArguments;");
        sb.AppendLine("        return rawArguments is not null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get the raw call-site argument text from the most recent completed child rule call result; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; the helper returns <c>false</c> when the last call result is for a different rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Receives the raw call-site argument text when present on the matching result.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result exists and carries non-null raw argument text; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Raw arguments are metadata only: not evaluated, not bound to child parameters.</remarks>");
        sb.AppendLine("    private bool TryGetLastRuleCallRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, out string? rawArguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        var result = _frameManager?.Current?.LastCompletedChildCall;");
        sb.AppendLine("        if (result is null || !string.Equals(result.RuleName, ruleName, global::System.StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.AppendLine("            rawArguments = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        rawArguments = result.RawArguments;");
        sb.AppendLine("        return rawArguments is not null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Splits raw call-site argument text into top-level argument slices.</summary>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw argument text as stored in <see cref=\"global::Utils.Parser.Runtime.ParserRuleCallResult.RawArguments\"/>; <c>null</c> returns an empty list.</param>");
        sb.AppendLine("    /// <returns>A read-only list of trimmed top-level argument slices, or an empty list when <paramref name=\"rawArguments\"/> is <c>null</c> or whitespace-only.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no argument is evaluated, no parameter is bound. See <see cref=\"global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel\"/> for splitting rules.</remarks>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<string> SplitRawArgumentsTopLevel(string? rawArguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        return rawArguments is null");
        sb.AppendLine("            ? global::System.Array.Empty<string>()");
        sb.AppendLine("            : global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel(rawArguments);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text from the most recent completed child rule call result into top-level slices.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; returns <c>false</c> when the last call result is for a different rule or carries no raw arguments.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the top-level argument slices when the helper returns <c>true</c>; otherwise an empty list.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with non-null raw arguments was found; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no argument is evaluated, no parameter is bound, no seed is set automatically.</remarks>");
        sb.AppendLine("    private static bool TrySplitLastRuleCallRawArguments(ParserRuleLifecycleContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyList<string> arguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments))");
        sb.AppendLine("        {");
        sb.AppendLine("            arguments = global::System.Array.Empty<string>();");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        arguments = global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel(rawArguments!);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text from the most recent completed child rule call result; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; returns <c>false</c> when the last call result is for a different rule or carries no raw arguments.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the top-level argument slices when the helper returns <c>true</c>; otherwise an empty list.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with non-null raw arguments was found; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no argument is evaluated, no parameter is bound, no seed is set automatically.</remarks>");
        sb.AppendLine("    private bool TrySplitLastRuleCallRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyList<string> arguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments))");
        sb.AppendLine("        {");
        sb.AppendLine("            arguments = global::System.Array.Empty<string>();");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        arguments = global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel(rawArguments!);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get an untyped return value by name from the most recent completed child rule call result.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"returnName\">The lexical return name as declared in the child rule (e.g. <c>\"value\"</c> for <c>returns [int value]</c>).</param>");
        sb.AppendLine("    /// <param name=\"value\">Receives the return value when present.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a call result exists and contains the named return; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks><c>$rule.value</c> and labeled return attributes are handled only by the generated embedded-code rewriter; typed returns and automatic return propagation are not supported.</remarks>");
        sb.AppendLine("    private static bool TryGetLastRuleCallReturn(ParserRuleLifecycleContext context, string returnName, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine();
        sb.AppendLine("        var result = context.InvocationFrame?.LastCompletedChildCall;");
        sb.AppendLine("        if (result is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result.Returns.TryGetValue(returnName, out value);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
