using System.Collections.Generic;
using System.Linq;
using System.Text;
using Utils.Parser.Diagnostics.EmbeddedCode;

namespace Utils.Parser.Generators.Internal;

internal static partial class GrammarEmitter
{


    /// <summary>
    /// Collects unscoped <c>@header</c> and <c>@parser::header</c> blocks that can be injected near the top of generated C# output.
    /// </summary>
    /// <param name="grammar">Parsed grammar AST.</param>
    /// <returns>Parser header actions in grammar order.</returns>
    private static IReadOnlyList<G4GrammarAction> CollectParserHeaders(G4Grammar grammar)
    {
        return grammar.Actions
            .Where(action => EmbeddedMembersSupport.IsInjectableParserHeaderAction(grammar, action))
            .ToArray();
    }

    /// <summary>
    /// Emits parser header blocks verbatim before generated type declarations so ordinary C# using directives remain valid.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    /// <param name="parserHeaders">Parser header blocks to inject.</param>
    /// <param name="grammar">Parsed grammar AST used for transformer context.</param>
    /// <param name="transformer">Parser embedded-code transformer used for parser headers.</param>
    private static void EmitParserHeaders(StringBuilder sb, IReadOnlyList<G4GrammarAction> parserHeaders, G4Grammar grammar, IParserEmbeddedCodeTransformer transformer)
    {
        foreach (var header in parserHeaders)
        {
            string code = TransformEmbeddedCode(transformer, header.RawCode, ParserEmbeddedCodeLocation.ParserHeader, grammar, null);
            sb.AppendLine("// <auto-generated-parser-header>");
            foreach (string line in SplitEmbeddedCodeLines(code))
            {
                sb.AppendLine(line);
            }
            sb.AppendLine("// </auto-generated-parser-header>");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Collects unscoped <c>@footer</c> and <c>@parser::footer</c> blocks that can be injected near the end of generated C# output.
    /// </summary>
    /// <param name="grammar">Grammar AST that may contain parser footer actions.</param>
    /// <returns>Parser footer actions in grammar order.</returns>
    private static IReadOnlyList<G4GrammarAction> CollectParserFooters(G4Grammar grammar)
    {
        return grammar.Actions
            .Where(action => EmbeddedMembersSupport.IsInjectableParserFooterAction(grammar, action))
            .ToArray();
    }

    /// <summary>
    /// Emits parser footer blocks verbatim after generated type declarations as trailing C# source.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    /// <param name="parserFooters">Parser footer blocks to inject.</param>
    /// <param name="grammar">Parsed grammar AST used for transformer context.</param>
    /// <param name="transformer">Parser embedded-code transformer used for parser footers.</param>
    private static void EmitParserFooters(StringBuilder sb, IReadOnlyList<G4GrammarAction> parserFooters, G4Grammar grammar, IParserEmbeddedCodeTransformer transformer)
    {
        foreach (var footer in parserFooters)
        {
            string code = TransformEmbeddedCode(transformer, footer.RawCode, ParserEmbeddedCodeLocation.ParserFooter, grammar, null);
            sb.AppendLine("// <auto-generated-parser-footer>");
            foreach (string line in SplitEmbeddedCodeLines(code))
            {
                sb.AppendLine(line);
            }

            sb.AppendLine("// </auto-generated-parser-footer>");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Collects unscoped <c>@members</c> and <c>@parser::members</c> blocks that can be injected into the parser execution context.
    /// </summary>
    /// <param name="grammar">Parsed grammar AST.</param>
    /// <returns>Parser members actions in grammar order.</returns>
    private static IReadOnlyList<G4GrammarAction> CollectParserMembers(G4Grammar grammar)
    {
        return grammar.Actions
            .Where(action => EmbeddedMembersSupport.IsInjectableParserMembersAction(grammar, action))
            .ToArray();
    }

    /// <summary>
    /// Emits parser members blocks verbatim into the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    /// <param name="parserMembers">Parser members blocks to inject.</param>
    /// <param name="grammar">Parsed grammar AST used for transformer context.</param>
    /// <param name="transformer">Parser embedded-code transformer used for parser members.</param>
    private static void EmitParserMembers(StringBuilder sb, IReadOnlyList<G4GrammarAction> parserMembers, G4Grammar grammar, IParserEmbeddedCodeTransformer transformer)
    {
        foreach (var members in parserMembers)
        {
            string code = TransformEmbeddedCode(transformer, members.RawCode, ParserEmbeddedCodeLocation.ParserMembers, grammar, null);
            sb.AppendLine("    // <auto-generated-parser-members>");
            foreach (string line in SplitEmbeddedCodeLines(code))
            {
                sb.AppendLine($"    {line}");
            }
            sb.AppendLine("    // </auto-generated-parser-members>");
            sb.AppendLine();
        }
    }
}
