using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Utils.Parser.Diagnostics.EmbeddedCode;

namespace Utils.Parser.Generators.Internal;

internal static partial class GrammarEmitter
{

    /// <summary>
    /// Emits explicit rule-local helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleLocalHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Gets a passive rule-local value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-local metadata name.</param>");
        sb.AppendLine("    /// <returns>The stored local value, or <c>null</c> when no invocation frame or local value is present.</returns>");
        sb.AppendLine("    /// <remarks>Declared locals are allocated separately before generated <c>@init</c> execution.</remarks>");
        sb.AppendLine("    private static object? GetRuleLocal(ParserRuleLifecycleContext context, string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        return TryGetRuleLocal(context, name, out object? value) ? value : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get a passive rule-local value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-local metadata name.</param>");
        sb.AppendLine("    /// <param name=\"value\">Receives the stored local value when one has been explicitly set.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when the invocation frame contains the named local; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>This helper observes only <c>context.InvocationFrame</c>; declared-local allocation is handled before generated <c>@init</c>.</remarks>");
        sb.AppendLine("    private static bool TryGetRuleLocal(ParserRuleLifecycleContext context, string name, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        if (context.InvocationFrame is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame.TryGetLocal(name, out value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a required typed rule-local value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    private static T GetRequiredRuleLocal<T>(ParserRuleLifecycleContext context, string localName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(localName);");
        sb.AppendLine("        if (context.InvocationFrame is null || !context.InvocationFrame.TryGetLocal(localName, out object? value))");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        return CastRequiredRuleAttribute<T>(\"$\" + localName, \"local\", localName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Ensures a declared rule-local slot exists on the active invocation frame before a typed write.</summary>");
        sb.AppendLine("    private static void EnsureRequiredRuleLocalPresent(ParserRuleInvocationFrame frame, string localName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (frame.TryGetLocal(localName, out _))");
        sb.AppendLine("        {");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (frame.Descriptor is not null && global::System.Linq.Enumerable.Any(frame.Descriptor.Locals, descriptor => string.Equals(descriptor.Name, localName, global::System.StringComparison.Ordinal)))");
        sb.AppendLine("        {");
        sb.AppendLine("            frame.SetLocal(localName, null);");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Stores a required typed rule-local value on the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    private static void SetRequiredRuleLocal<T>(ParserRuleLifecycleContext context, string localName, T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(localName);");
        sb.AppendLine("        if (context.InvocationFrame is null)");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        EnsureRequiredRuleLocalPresent(context.InvocationFrame, localName);");
        sb.AppendLine("        context.InvocationFrame.SetLocal(localName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Stores a passive rule-local value on the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to update.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-local metadata name.</param>");
        sb.AppendLine("    /// <param name=\"value\">Value to store in the invocation-frame locals dictionary.</param>");
        sb.AppendLine("    /// <remarks>If no invocation frame is available, this helper performs no work and does not allocate a frame.</remarks>");
        sb.AppendLine("    private static void SetRuleLocal(ParserRuleLifecycleContext context, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        context.InvocationFrame?.SetLocal(name, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets passive rule-local declaration descriptors from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying descriptor metadata.</param>");
        sb.AppendLine("    /// <returns>Rule-local declaration descriptors, or an empty list when no descriptor metadata is available.</returns>");
        sb.AppendLine("    /// <remarks>The descriptors contain raw declarations only; generated code does not infer C# types or create typed locals.</remarks>");
        sb.AppendLine("    private static IReadOnlyList<ParserRuleLocalDescriptor> GetRuleLocalDescriptors(ParserRuleLifecycleContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame?.Descriptor?.Locals ?? global::System.Array.Empty<ParserRuleLocalDescriptor>();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Allocates missing declared rule locals as untyped null entries on the active invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame and passive local descriptors.</param>");
        sb.AppendLine("    /// <remarks>Existing values are preserved, and no target-language type or default value is inferred.</remarks>");
        sb.AppendLine("    private static void AllocateDeclaredRuleLocals(ParserRuleLifecycleContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine();
        sb.AppendLine("        ParserRuleInvocationFrame? frame = context.InvocationFrame;");
        sb.AppendLine("        if (frame?.Descriptor is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (ParserRuleLocalDescriptor descriptor in frame.Descriptor.Locals)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!string.IsNullOrEmpty(descriptor.Name) && !frame.TryGetLocal(descriptor.Name, out _))");
        sb.AppendLine("            {");
        sb.AppendLine("                frame.SetLocal(descriptor.Name, null);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits explicit rule-return helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleReturnHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Gets an untyped rule-return value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-return metadata name.</param>");
        sb.AppendLine("    /// <returns>The stored return value, or <c>null</c> when no invocation frame or return value is present.</returns>");
        sb.AppendLine("    /// <remarks>Returns are not propagated to caller frames. Generated <c>Parse(...)</c> remains conservative.</remarks>");
        sb.AppendLine("    private static object? GetRuleReturn(ParserRuleLifecycleContext context, string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        return TryGetRuleReturn(context, name, out object? value) ? value : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get an untyped rule-return value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-return metadata name.</param>");
        sb.AppendLine("    /// <param name=\"value\">Receives the stored return value when one has been explicitly set.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when the invocation frame contains the named return; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Returns are not propagated to caller frames. Return values must be written explicitly via <c>SetRuleReturn</c>.</remarks>");
        sb.AppendLine("    private static bool TryGetRuleReturn(ParserRuleLifecycleContext context, string name, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        if (context.InvocationFrame is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame.TryGetReturnValue(name, out value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a required current-rule return while preserving present-null values.</summary>");
        sb.AppendLine("    private static object? GetRequiredRuleReturn(ParserRuleLifecycleContext context, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        if (context.InvocationFrame is not null && context.InvocationFrame.TryGetReturnValue(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + context.RuleName + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a typed required current-rule return while preserving present-null values.</summary>");
        sb.AppendLine("    private static T GetRequiredRuleReturn<T>(ParserRuleLifecycleContext context, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (T)GetRequiredRuleReturn(context, returnName)!;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Ensures a declared rule-return slot exists on the active invocation frame before a typed write.</summary>");
        sb.AppendLine("    private static void EnsureRequiredRuleReturnPresent(ParserRuleInvocationFrame frame, string returnName, string ruleName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (frame.TryGetReturnValue(returnName, out _))");
        sb.AppendLine("        {");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (frame.Descriptor is not null && global::System.Linq.Enumerable.Any(frame.Descriptor.Returns, descriptor => string.Equals(descriptor.Name, returnName, global::System.StringComparison.Ordinal)))");
        sb.AppendLine("        {");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + ruleName + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not declared on the current rule invocation."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Stores a typed rule-return value on the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    private static void SetRequiredRuleReturn<T>(ParserRuleLifecycleContext context, string returnName, T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        if (context.InvocationFrame is null)");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + context.RuleName + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        EnsureRequiredRuleReturnPresent(context.InvocationFrame, returnName, context.RuleName);");
        sb.AppendLine("        context.InvocationFrame.SetReturnValue(returnName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Stores an untyped rule-return value on the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to update.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-return metadata name.</param>");
        sb.AppendLine("    /// <param name=\"value\">Value to store in the invocation-frame returns dictionary.</param>");
        sb.AppendLine("    /// <remarks>If no invocation frame is available, this helper performs no work. Returns are not propagated to caller frames automatically.</remarks>");
        sb.AppendLine("    private static void SetRuleReturn(ParserRuleLifecycleContext context, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        context.InvocationFrame?.SetReturnValue(name, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets passive rule-return declaration descriptors from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying descriptor metadata.</param>");
        sb.AppendLine("    /// <returns>Rule-return declaration descriptors, or an empty list when no descriptor metadata is available.</returns>");
        sb.AppendLine("    /// <remarks>The descriptors contain raw declarations only; no typed return properties or implicit variables are generated.</remarks>");
        sb.AppendLine("    private static IReadOnlyList<ParserRuleReturnDescriptor> GetRuleReturnDescriptors(ParserRuleLifecycleContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame?.Descriptor?.Returns ?? global::System.Array.Empty<ParserRuleReturnDescriptor>();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits explicit rule-parameter helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleParameterHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Gets an untyped rule-parameter value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-parameter metadata name.</param>");
        sb.AppendLine("    /// <returns>The stored parameter value, or <c>null</c> when no invocation frame or parameter value is present.</returns>");
        sb.AppendLine("    /// <remarks>Parameters are not auto-bound. Rule call arguments are not evaluated by this untyped helper; read-only <c>$param</c> uses a generated typed required helper when descriptor metadata exposes a raw type.</remarks>");
        sb.AppendLine("    private static object? GetRuleParameter(ParserRuleLifecycleContext context, string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        return TryGetRuleParameter(context, name, out object? value) ? value : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get an untyped rule-parameter value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"name\">Rule-parameter metadata name.</param>");
        sb.AppendLine("    /// <param name=\"value\">Receives the stored parameter value when explicitly present on the frame.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when the invocation frame contains the named parameter; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Returns <c>false</c> when no argument was explicitly supplied. Parameters are not auto-bound.</remarks>");
        sb.AppendLine("    private static bool TryGetRuleParameter(ParserRuleLifecycleContext context, string name, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine();
        sb.AppendLine("        if (context.InvocationFrame is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame.TryGetParameter(name, out value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a required typed rule-parameter value from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    private static T GetRequiredRuleParameter<T>(ParserRuleLifecycleContext context, string parameterName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        if (context.InvocationFrame is null || !context.InvocationFrame.TryGetParameter(parameterName, out object? value))");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + parameterName, parameterName, ""Rule parameter '"" + parameterName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        return CastRequiredRuleAttribute<T>(\"$\" + parameterName, \"parameter\", parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Casts a required typed rule attribute value and reports deterministic attribute access failures.</summary>");
        sb.AppendLine("    private static T CastRequiredRuleAttribute<T>(string attributeText, string attributeKind, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value is T typed) return typed;");
        sb.AppendLine("        if (value is null && default(T) is null) return default!;");
        sb.AppendLine(@"        string actualType = value is null ? ""null"" : value.GetType().FullName ?? value.GetType().Name;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(attributeText, name, ""Rule "" + attributeKind + "" '"" + name + ""' cannot be read as '"" + typeof(T).FullName + ""' because the stored value is '"" + actualType + ""'."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets passive rule-parameter declaration descriptors from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying descriptor metadata.</param>");
        sb.AppendLine("    /// <returns>Rule-parameter declaration descriptors, or an empty list when no descriptor metadata is available.</returns>");
        sb.AppendLine("    /// <remarks>Descriptors contain raw declarations only. No typed parameter fields/properties are generated.</remarks>");
        sb.AppendLine("    private static IReadOnlyList<ParserRuleParameterDescriptor> GetRuleParameterDescriptors(ParserRuleLifecycleContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame?.Descriptor?.Parameters ?? global::System.Array.Empty<ParserRuleParameterDescriptor>();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits explicit rule call-result helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleCallResultHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Attempts to get the retained result for an assignment-labeled successful child call.</summary>");
        sb.AppendLine("    private static bool TryGetLabeledRuleCallResult(ParserRuleLifecycleContext context, string labelName, out global::Utils.Parser.Runtime.ParserRuleCallResult result)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (context.InvocationFrame?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).TryGetAssignment(labelName, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets retained results for a list-labeled child call in successful execution order.</summary>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<global::Utils.Parser.Runtime.ParserRuleCallResult> GetLabeledRuleCallResults(ParserRuleLifecycleContext context, string labelName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (context.InvocationFrame?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).GetList(labelName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get an ordinal named return from an assignment-labeled child result, preserving present-null values.</summary>");
        sb.AppendLine("    private static bool TryGetLabeledRuleCallReturn(ParserRuleLifecycleContext context, string labelName, string returnName, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        if (TryGetLabeledRuleCallResult(context, labelName, out var result)) return result.TryGetReturn(returnName, out value);");
        sb.AppendLine("        value = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a required assignment-labeled child return while preserving present-null values.</summary>");
        sb.AppendLine("    private static object? GetRequiredLabeledRuleCallReturn(ParserRuleLifecycleContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine(@"        if (!TryGetLabeledRuleCallResult(context, labelName, out var result)) throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Assignment label '"" + labelName + ""' is not available in the current rule invocation."");");
        sb.AppendLine("        if (result.TryGetReturn(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Return '"" + returnName + ""' is not available on assignment label '"" + labelName + ""'."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets present ordinal named returns from list-labeled child results in call order; results missing the return are skipped and present-null values are included.</summary>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<object?> GetLabeledRuleCallReturns(ParserRuleLifecycleContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var values = new global::System.Collections.Generic.List<object?>();");
        sb.AppendLine("        foreach (var result in GetLabeledRuleCallResults(context, labelName)) if (result.TryGetReturn(returnName, out object? value)) values.Add(value);");
        sb.AppendLine("        return values.AsReadOnly();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for storing a passive rule-local value on the current invocation frame.</summary>");
        sb.AppendLine("    private void SetRuleLocal(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(name);");
        sb.AppendLine("        _frameManager?.Current?.SetLocal(name, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required typed rule-parameter access.</summary>");
        sb.AppendLine("    private T GetRequiredRuleParameter<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string parameterName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null || !frame.TryGetParameter(parameterName, out object? value))");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + parameterName, parameterName, ""Rule parameter '"" + parameterName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        return CastRequiredRuleAttribute<T>(\"$\" + parameterName, \"parameter\", parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required typed rule-local access.</summary>");
        sb.AppendLine("    private T GetRequiredRuleLocal<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string localName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(localName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null || !frame.TryGetLocal(localName, out object? value))");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        return CastRequiredRuleAttribute<T>(\"$\" + localName, \"local\", localName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for storing a required typed rule-local value on the current invocation frame.</summary>");
        sb.AppendLine("    private void SetRequiredRuleLocal<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string localName, T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(localName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null)");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + localName, localName, ""Rule local '"" + localName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        EnsureRequiredRuleLocalPresent(frame, localName);");
        sb.AppendLine("        frame.SetLocal(localName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for assignment-labeled child result access.</summary>");
        sb.AppendLine("    private bool TryGetLabeledRuleCallResult(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, out global::Utils.Parser.Runtime.ParserRuleCallResult result)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (_frameManager?.Current?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).TryGetAssignment(labelName, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for ordered list-labeled child result access.</summary>");
        sb.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<global::Utils.Parser.Runtime.ParserRuleCallResult> GetLabeledRuleCallResults(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        return (_frameManager?.Current?.LabeledCallResults ?? global::Utils.Parser.Runtime.ParserLabeledRuleCallResultStore.Empty).GetList(labelName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for assignment-labeled child return access.</summary>");
        sb.AppendLine("    private bool TryGetLabeledRuleCallReturn(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, string returnName, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        if (TryGetLabeledRuleCallResult(context, labelName, out var result)) return result.TryGetReturn(returnName, out value);");
        sb.AppendLine("        value = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required assignment-labeled child return access.</summary>");
        sb.AppendLine("    private object? GetRequiredLabeledRuleCallReturn(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine(@"        if (!TryGetLabeledRuleCallResult(context, labelName, out var result)) throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Assignment label '"" + labelName + ""' is not available in the current rule invocation."");");
        sb.AppendLine("        if (result.TryGetReturn(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + labelName + ""."" + returnName, labelName, returnName, ""Return '"" + returnName + ""' is not available on assignment label '"" + labelName + ""'."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for required current-rule return access.</summary>");
        sb.AppendLine("    private object? GetRequiredRuleReturn(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is not null && frame.TryGetReturnValue(returnName, out object? value)) return value;");
        sb.AppendLine(@"        throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + context.Rule.Name + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for typed required current-rule return access.</summary>");
        sb.AppendLine("    private T GetRequiredRuleReturn<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (T)GetRequiredRuleReturn(context, returnName)!;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload for storing a required typed current-rule return on the active invocation frame.</summary>");
        sb.AppendLine("    private void SetRequiredRuleReturn<T>(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string returnName, T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var frame = _frameManager?.Current;");
        sb.AppendLine("        if (frame is null)");
        sb.AppendLine("        {");
        sb.AppendLine(@"            throw new global::Utils.Parser.Runtime.ParserAttributeAccessException(""$"" + context.Rule.Name + ""."" + returnName, returnName, ""Return '"" + returnName + ""' is not available on the current rule invocation."");");
        sb.AppendLine("        }");
        sb.AppendLine("        EnsureRequiredRuleReturnPresent(frame, returnName, context.Rule.Name);");
        sb.AppendLine("        frame.SetReturnValue(returnName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Inline-action overload returning present list-labeled child returns in call order, skipping absent returns.</summary>");
        sb.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<object?> GetLabeledRuleCallReturns(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string labelName, string returnName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(labelName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine("        var values = new global::System.Collections.Generic.List<object?>();");
        sb.AppendLine("        foreach (var result in GetLabeledRuleCallResults(context, labelName)) if (result.TryGetReturn(returnName, out object? value)) values.Add(value);");
        sb.AppendLine("        return values.AsReadOnly();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the most recent completed child rule call result from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <returns>The last completed child call result, or <c>null</c> when no child rule has yet completed successfully or no frame is available.</returns>");
        sb.AppendLine("    /// <remarks>Returns are not propagated automatically. Limited read-only parser return attributes project the same rollback-safe frame state; no implicit variables are generated.</remarks>");
        sb.AppendLine("    private static global::Utils.Parser.Runtime.ParserRuleCallResult? GetLastRuleCallResult(ParserRuleLifecycleContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine();
        sb.AppendLine("        return context.InvocationFrame?.LastCompletedChildCall;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get the raw call-site argument text from the most recent completed child rule call result.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; the helper returns <c>false</c> when the last call result is for a different rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Receives the raw call-site argument text when present on the matching result.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result exists and carries non-null raw argument text; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Raw arguments are metadata only: not evaluated, not bound to child parameters. Use <c>SetNextRuleParameter(...)</c> for explicit seeding.</remarks>");
        sb.AppendLine("    private static bool TryGetLastRuleCallRawArguments(ParserRuleLifecycleContext context, string ruleName, out string? rawArguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        var result = context.InvocationFrame?.LastCompletedChildCall;");
        sb.AppendLine("        if (result is null || !string.Equals(result.RuleName, ruleName, global::System.StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.AppendLine("            rawArguments = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        rawArguments = result.RawArguments;");
        sb.AppendLine("        return rawArguments is not null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get the raw call-site argument text from the most recent completed child rule call result; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; the helper returns <c>false</c> when the last call result is for a different rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Receives the raw call-site argument text when present on the matching result.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result exists and carries non-null raw argument text; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Raw arguments are metadata only: not evaluated, not bound to child parameters.</remarks>");
        sb.AppendLine("    private bool TryGetLastRuleCallRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, out string? rawArguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        var result = _frameManager?.Current?.LastCompletedChildCall;");
        sb.AppendLine("        if (result is null || !string.Equals(result.RuleName, ruleName, global::System.StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.AppendLine("            rawArguments = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        rawArguments = result.RawArguments;");
        sb.AppendLine("        return rawArguments is not null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Splits raw call-site argument text into top-level argument slices.</summary>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw argument text as stored in <see cref=\"global::Utils.Parser.Runtime.ParserRuleCallResult.RawArguments\"/>; <c>null</c> returns an empty list.</param>");
        sb.AppendLine("    /// <returns>A read-only list of trimmed top-level argument slices, or an empty list when <paramref name=\"rawArguments\"/> is <c>null</c> or whitespace-only.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no argument is evaluated, no parameter is bound. See <see cref=\"global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel\"/> for splitting rules.</remarks>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<string> SplitRawArgumentsTopLevel(string? rawArguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        return rawArguments is null");
        sb.AppendLine("            ? global::System.Array.Empty<string>()");
        sb.AppendLine("            : global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel(rawArguments);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text from the most recent completed child rule call result into top-level slices.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; returns <c>false</c> when the last call result is for a different rule or carries no raw arguments.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the top-level argument slices when the helper returns <c>true</c>; otherwise an empty list.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with non-null raw arguments was found; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no argument is evaluated, no parameter is bound, no seed is set automatically.</remarks>");
        sb.AppendLine("    private static bool TrySplitLastRuleCallRawArguments(ParserRuleLifecycleContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyList<string> arguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments))");
        sb.AppendLine("        {");
        sb.AppendLine("            arguments = global::System.Array.Empty<string>();");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        arguments = global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel(rawArguments!);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text from the most recent completed child rule call result; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; returns <c>false</c> when the last call result is for a different rule or carries no raw arguments.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the top-level argument slices when the helper returns <c>true</c>; otherwise an empty list.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with non-null raw arguments was found; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no argument is evaluated, no parameter is bound, no seed is set automatically.</remarks>");
        sb.AppendLine("    private bool TrySplitLastRuleCallRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyList<string> arguments)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments))");
        sb.AppendLine("        {");
        sb.AppendLine("            arguments = global::System.Array.Empty<string>();");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        arguments = global::Utils.Parser.Runtime.ParserRawArgumentSplitter.SplitTopLevel(rawArguments!);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to get an untyped return value by name from the most recent completed child rule call result.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"returnName\">The lexical return name as declared in the child rule (e.g. <c>\"value\"</c> for <c>returns [int value]</c>).</param>");
        sb.AppendLine("    /// <param name=\"value\">Receives the return value when present.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a call result exists and contains the named return; otherwise, <c>false</c>.</returns>");
        sb.AppendLine("    /// <remarks><c>$rule.value</c> and labeled return attributes are handled only by the generated embedded-code rewriter; typed returns and automatic return propagation are not supported.</remarks>");
        sb.AppendLine("    private static bool TryGetLastRuleCallReturn(ParserRuleLifecycleContext context, string returnName, out object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(returnName);");
        sb.AppendLine();
        sb.AppendLine("        var result = context.InvocationFrame?.LastCompletedChildCall;");
        sb.AppendLine("        if (result is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result.Returns.TryGetValue(returnName, out value);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits explicit next-child-rule parameter seeding helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleSeedingHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Seeds an untyped parameter value for the next invocation of the named child rule from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"value\">Untyped value to seed.</param>");
        sb.AppendLine("    /// <remarks>This is not ANTLR-compatible argument passing. <c>callee[expr]</c> is not evaluated. Seeds are rollback-safe when the managed execution-state mechanism is active.</remarks>");
        sb.AppendLine("    private static void SetNextRuleParameter(ParserRuleLifecycleContext context, string ruleName, string parameterName, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine();
        sb.AppendLine("        context.InvocationFrame?.SetPendingChildParameter(ruleName, parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Removes all pending parameter seeds for the named child rule from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule whose seeds to clear.</param>");
        sb.AppendLine("    /// <remarks>If no seeds are pending for <paramref name=\"ruleName\"/>, this helper performs no work.</remarks>");
        sb.AppendLine("    private static void ClearNextRuleParameters(ParserRuleLifecycleContext context, string ruleName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        context.InvocationFrame?.ClearPendingChildParameters(ruleName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Seeds an untyped parameter value for the next invocation of the named child rule; inline-action overload that routes through the active frame manager.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"value\">Untyped value to seed.</param>");
        sb.AppendLine("    /// <remarks>This is not ANTLR-compatible argument passing. Seeds are rollback-safe when the managed execution-state mechanism is active.</remarks>");
        sb.AppendLine("    private void SetNextRuleParameter(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, string parameterName, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine();
        sb.AppendLine("        _frameManager?.SetPendingChildParameter(ruleName, parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Removes all pending parameter seeds for the named child rule; inline-action overload that routes through the active frame manager.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule whose seeds to clear.</param>");
        sb.AppendLine("    /// <remarks>If no seeds are pending for <paramref name=\"ruleName\"/>, this helper performs no work.</remarks>");
        sb.AppendLine("    private void ClearNextRuleParameters(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        _frameManager?.ClearPendingChildParameters(ruleName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps raw call-site argument text and seeds it as a parameter for the next invocation of the named child rule.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw call-site argument text to map; when <c>null</c>, returns <c>false</c> and no seed is set.</param>");
        sb.AppendLine("    /// <param name=\"map\">Caller-supplied delegate that converts the raw text to an untyped seed value. Must not be <c>null</c>. Exceptions from the delegate propagate to the caller.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when <paramref name=\"rawArguments\"/> was non-null and a seed was set; <c>false</c> when <paramref name=\"rawArguments\"/> was <c>null</c>.</returns>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// This helper requires an explicit mapper — it does not evaluate <c>callee[...]</c> automatically.");
        sb.AppendLine("    /// The seed targets the <em>next</em> invocation of <paramref name=\"ruleName\"/>; call this helper before that invocation occurs.");
        sb.AppendLine("    /// Seeds are rollback-safe when the managed execution-state mechanism is active.");
        sb.AppendLine("    /// Bare <c>$param</c> generated embedded-code reads are separate from this helper. Automatic argument passing is not implemented.");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    private static bool SetNextRuleParameterFromRawArguments(ParserRuleLifecycleContext context, string ruleName, string parameterName, string? rawArguments, global::System.Func<string, object?> map)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(map);");
        sb.AppendLine();
        sb.AppendLine("        if (rawArguments is null) return false;");
        sb.AppendLine();
        sb.AppendLine("        SetNextRuleParameter(context, ruleName, parameterName, map(rawArguments));");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps raw call-site argument text and seeds it as a parameter for the next invocation of the named child rule; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw call-site argument text to map; when <c>null</c>, returns <c>false</c> and no seed is set.</param>");
        sb.AppendLine("    /// <param name=\"map\">Caller-supplied delegate that converts the raw text to an untyped seed value. Must not be <c>null</c>. Exceptions from the delegate propagate to the caller.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when <paramref name=\"rawArguments\"/> was non-null and a seed was set; <c>false</c> when <paramref name=\"rawArguments\"/> was <c>null</c>.</returns>");
        sb.AppendLine("    /// <remarks>This is not ANTLR-compatible argument passing. Seeds are rollback-safe when the managed execution-state mechanism is active.</remarks>");
        sb.AppendLine("    private bool SetNextRuleParameterFromRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, string parameterName, string? rawArguments, global::System.Func<string, object?> map)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(map);");
        sb.AppendLine();
        sb.AppendLine("        if (rawArguments is null) return false;");
        sb.AppendLine();
        sb.AppendLine("        _frameManager?.SetPendingChildParameter(ruleName, parameterName, map(rawArguments));");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps multiple positional raw call-site argument slices to named child-rule parameter seeds in a single call.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seeds when next entered.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Pre-split argument slices, e.g. from <c>TrySplitLastRuleCallRawArguments</c>. Must not be <c>null</c>.</param>");
        sb.AppendLine("    /// <param name=\"mappings\">One or more positional mappings. Each specifies a parameter name, a zero-based slice index, and a mapper delegate.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when all mappings were applied; <c>false</c> when any mapping index is out of range (no seed is set for any mapping in that case).</returns>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// Validation runs before any seed is applied: if any index is out of range the helper returns <c>false</c> and no seed is written.");
        sb.AppendLine("    /// Duplicate parameter names are allowed; the last mapping for a given name wins.");
        sb.AppendLine("    /// Mapper exceptions propagate. Null mapped values are seeded as-is.");
        sb.AppendLine("    /// This is not ANTLR-compatible argument passing. Seeds are rollback-safe when the managed execution-state mechanism is active.");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    private static bool SetNextRuleParametersFromRawArguments(ParserRuleLifecycleContext context, string ruleName, global::System.Collections.Generic.IReadOnlyList<string> rawArguments, params global::Utils.Parser.Runtime.ParserRawArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(rawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (m.Index < 0 || m.Index >= rawArguments.Count) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            SetNextRuleParameter(context, ruleName, m.ParameterName, m.Map(rawArguments[m.Index]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps multiple positional raw call-site argument slices to named child-rule parameter seeds; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seeds when next entered.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Pre-split argument slices. Must not be <c>null</c>.</param>");
        sb.AppendLine("    /// <param name=\"mappings\">One or more positional mappings.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when all mappings were applied; <c>false</c> when any mapping index is out of range (no seed is set for any mapping in that case).</returns>");
        sb.AppendLine("    /// <remarks>Seeds are rollback-safe when the managed execution-state mechanism is active. This is not ANTLR-compatible argument passing.</remarks>");
        sb.AppendLine("    private bool SetNextRuleParametersFromRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, global::System.Collections.Generic.IReadOnlyList<string> rawArguments, params global::Utils.Parser.Runtime.ParserRawArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(rawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (m.Index < 0 || m.Index >= rawArguments.Count) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            _frameManager?.SetPendingChildParameter(ruleName, m.ParameterName, m.Map(rawArguments[m.Index]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Named raw argument helpers ──────────────────────────────────────────────────────────

        sb.AppendLine("    /// <summary>Splits raw call-site argument text into named top-level key–value pairs.</summary>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw argument text; <c>null</c> returns an empty dictionary.</param>");
        sb.AppendLine("    /// <param name=\"separatorMode\">Which separator to recognise. Defaults to colon-or-equals.</param>");
        sb.AppendLine("    /// <returns>A dictionary of trimmed name–value pairs, or an empty dictionary when <paramref name=\"rawArguments\"/> is <c>null</c> or whitespace-only.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no value is evaluated, no parameter is bound. Separator inside nesting or quotes is ignored. Missing separator throws <see cref=\"global::System.FormatException\"/>.</remarks>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string> SplitNamedRawArgumentsTopLevel(string? rawArguments, global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode separatorMode = global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode.ColonOrEquals)");
        sb.AppendLine("    {");
        sb.AppendLine("        return rawArguments is null");
        sb.AppendLine("            ? new global::System.Collections.Generic.Dictionary<string, string>()");
        sb.AppendLine("            : global::Utils.Parser.Runtime.ParserRawNamedArgumentSplitter.SplitNamedTopLevel(rawArguments, separatorMode);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text from the most recent completed child rule call result into named key–value pairs.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; returns <c>false</c> when mismatched or raw arguments absent.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the name–value dictionary when the helper returns <c>true</c>; otherwise an empty dictionary.</param>");
        sb.AppendLine("    /// <param name=\"separatorMode\">Which separator to recognise.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with parseable named arguments was found; <c>false</c> otherwise.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no value is evaluated, no parameter is bound.</remarks>");
        sb.AppendLine("    private static bool TrySplitLastRuleCallNamedRawArguments(ParserRuleLifecycleContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyDictionary<string, string> arguments, global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode separatorMode = global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode.ColonOrEquals)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        arguments = new global::System.Collections.Generic.Dictionary<string, string>();");
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments)) return false;");
        sb.AppendLine("        try { arguments = global::Utils.Parser.Runtime.ParserRawNamedArgumentSplitter.SplitNamedTopLevel(rawArguments!, separatorMode); return true; }");
        sb.AppendLine("        catch (global::System.FormatException) { arguments = new global::System.Collections.Generic.Dictionary<string, string>(); return false; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text into named pairs; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the name–value dictionary when the helper returns <c>true</c>.</param>");
        sb.AppendLine("    /// <param name=\"separatorMode\">Which separator to recognise.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with parseable named arguments was found; <c>false</c> otherwise.</returns>");
        sb.AppendLine("    private bool TrySplitLastRuleCallNamedRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyDictionary<string, string> arguments, global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode separatorMode = global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode.ColonOrEquals)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        arguments = new global::System.Collections.Generic.Dictionary<string, string>();");
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments)) return false;");
        sb.AppendLine("        try { arguments = global::Utils.Parser.Runtime.ParserRawNamedArgumentSplitter.SplitNamedTopLevel(rawArguments!, separatorMode); return true; }");
        sb.AppendLine("        catch (global::System.FormatException) { arguments = new global::System.Collections.Generic.Dictionary<string, string>(); return false; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps named raw argument entries to child-rule parameter seeds using explicit caller-supplied mapper delegates.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule.</param>");
        sb.AppendLine("    /// <param name=\"namedRawArguments\">Named argument dictionary from <c>TrySplitLastRuleCallNamedRawArguments</c>.</param>");
        sb.AppendLine("    /// <param name=\"mappings\">One or more named mappings. Validated before any seed is applied.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when all mappings were applied; <c>false</c> when any argument name is absent (no partial seeding).</returns>");
        sb.AppendLine("    /// <remarks>Duplicate ParameterName: last mapping wins. Mapper exceptions propagate. Null mapped values allowed.</remarks>");
        sb.AppendLine("    private static bool SetNextRuleParametersFromNamedRawArguments(ParserRuleLifecycleContext context, string ruleName, global::System.Collections.Generic.IReadOnlyDictionary<string, string> namedRawArguments, params global::Utils.Parser.Runtime.ParserRawNamedArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(namedRawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ArgumentName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (!namedRawArguments.ContainsKey(m.ArgumentName)) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            SetNextRuleParameter(context, ruleName, m.ParameterName, m.Map(namedRawArguments[m.ArgumentName]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps named raw argument entries to child-rule parameter seeds; inline-action overload.</summary>");
        sb.AppendLine("    private bool SetNextRuleParametersFromNamedRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, global::System.Collections.Generic.IReadOnlyDictionary<string, string> namedRawArguments, params global::Utils.Parser.Runtime.ParserRawNamedArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(namedRawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ArgumentName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (!namedRawArguments.ContainsKey(m.ArgumentName)) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            _frameManager?.SetPendingChildParameter(ruleName, m.ParameterName, m.Map(namedRawArguments[m.ArgumentName]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
