using System.Text;

namespace Utils.Parser.Generators.Internal;

internal static partial class GrammarEmitter
{

    /// <summary>
    /// Emits explicit next-child-rule parameter seeding helper methods on the generated execution context.
    /// </summary>
    /// <param name="sb">Source builder receiving generated C#.</param>
    private static void EmitRuleSeedingHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Seeds an untyped parameter value for the next invocation of the named child rule from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"value\">Untyped value to seed.</param>");
        sb.AppendLine("    /// <remarks>This is not ANTLR-compatible argument passing. <c>callee[expr]</c> is not evaluated. Seeds are rollback-safe when the managed execution-state mechanism is active.</remarks>");
        sb.AppendLine("    private static void SetNextRuleParameter(ParserRuleLifecycleContext context, string ruleName, string parameterName, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine();
        sb.AppendLine("        context.InvocationFrame?.SetPendingChildParameter(ruleName, parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Removes all pending parameter seeds for the named child rule from the active lifecycle invocation frame.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule whose seeds to clear.</param>");
        sb.AppendLine("    /// <remarks>If no seeds are pending for <paramref name=\"ruleName\"/>, this helper performs no work.</remarks>");
        sb.AppendLine("    private static void ClearNextRuleParameters(ParserRuleLifecycleContext context, string ruleName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        context.InvocationFrame?.ClearPendingChildParameters(ruleName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Seeds an untyped parameter value for the next invocation of the named child rule; inline-action overload that routes through the active frame manager.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"value\">Untyped value to seed.</param>");
        sb.AppendLine("    /// <remarks>This is not ANTLR-compatible argument passing. Seeds are rollback-safe when the managed execution-state mechanism is active.</remarks>");
        sb.AppendLine("    private void SetNextRuleParameter(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, string parameterName, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine();
        sb.AppendLine("        _frameManager?.SetPendingChildParameter(ruleName, parameterName, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Removes all pending parameter seeds for the named child rule; inline-action overload that routes through the active frame manager.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule whose seeds to clear.</param>");
        sb.AppendLine("    /// <remarks>If no seeds are pending for <paramref name=\"ruleName\"/>, this helper performs no work.</remarks>");
        sb.AppendLine("    private void ClearNextRuleParameters(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        _frameManager?.ClearPendingChildParameters(ruleName);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps raw call-site argument text and seeds it as a parameter for the next invocation of the named child rule.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw call-site argument text to map; when <c>null</c>, returns <c>false</c> and no seed is set.</param>");
        sb.AppendLine("    /// <param name=\"map\">Caller-supplied delegate that converts the raw text to an untyped seed value. Must not be <c>null</c>. Exceptions from the delegate propagate to the caller.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when <paramref name=\"rawArguments\"/> was non-null and a seed was set; <c>false</c> when <paramref name=\"rawArguments\"/> was <c>null</c>.</returns>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// This helper requires an explicit mapper — it does not evaluate <c>callee[...]</c> automatically.");
        sb.AppendLine("    /// The seed targets the <em>next</em> invocation of <paramref name=\"ruleName\"/>; call this helper before that invocation occurs.");
        sb.AppendLine("    /// Seeds are rollback-safe when the managed execution-state mechanism is active.");
        sb.AppendLine("    /// Bare <c>$param</c> generated embedded-code reads are separate from this helper. Automatic argument passing is not implemented.");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    private static bool SetNextRuleParameterFromRawArguments(ParserRuleLifecycleContext context, string ruleName, string parameterName, string? rawArguments, global::System.Func<string, object?> map)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(map);");
        sb.AppendLine();
        sb.AppendLine("        if (rawArguments is null) return false;");
        sb.AppendLine();
        sb.AppendLine("        SetNextRuleParameter(context, ruleName, parameterName, map(rawArguments));");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps raw call-site argument text and seeds it as a parameter for the next invocation of the named child rule; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seed when next entered.</param>");
        sb.AppendLine("    /// <param name=\"parameterName\">Parameter metadata name as declared in the child rule.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw call-site argument text to map; when <c>null</c>, returns <c>false</c> and no seed is set.</param>");
        sb.AppendLine("    /// <param name=\"map\">Caller-supplied delegate that converts the raw text to an untyped seed value. Must not be <c>null</c>. Exceptions from the delegate propagate to the caller.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when <paramref name=\"rawArguments\"/> was non-null and a seed was set; <c>false</c> when <paramref name=\"rawArguments\"/> was <c>null</c>.</returns>");
        sb.AppendLine("    /// <remarks>This is not ANTLR-compatible argument passing. Seeds are rollback-safe when the managed execution-state mechanism is active.</remarks>");
        sb.AppendLine("    private bool SetNextRuleParameterFromRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, string parameterName, string? rawArguments, global::System.Func<string, object?> map)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(parameterName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(map);");
        sb.AppendLine();
        sb.AppendLine("        if (rawArguments is null) return false;");
        sb.AppendLine();
        sb.AppendLine("        _frameManager?.SetPendingChildParameter(ruleName, parameterName, map(rawArguments));");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps multiple positional raw call-site argument slices to named child-rule parameter seeds in a single call.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seeds when next entered.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Pre-split argument slices, e.g. from <c>TrySplitLastRuleCallRawArguments</c>. Must not be <c>null</c>.</param>");
        sb.AppendLine("    /// <param name=\"mappings\">One or more positional mappings. Each specifies a parameter name, a zero-based slice index, and a mapper delegate.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when all mappings were applied; <c>false</c> when any mapping index is out of range (no seed is set for any mapping in that case).</returns>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// Validation runs before any seed is applied: if any index is out of range the helper returns <c>false</c> and no seed is written.");
        sb.AppendLine("    /// Duplicate parameter names are allowed; the last mapping for a given name wins.");
        sb.AppendLine("    /// Mapper exceptions propagate. Null mapped values are seeded as-is.");
        sb.AppendLine("    /// This is not ANTLR-compatible argument passing. Seeds are rollback-safe when the managed execution-state mechanism is active.");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    private static bool SetNextRuleParametersFromRawArguments(ParserRuleLifecycleContext context, string ruleName, global::System.Collections.Generic.IReadOnlyList<string> rawArguments, params global::Utils.Parser.Runtime.ParserRawArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(rawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (m.Index < 0 || m.Index >= rawArguments.Count) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            SetNextRuleParameter(context, ruleName, m.ParameterName, m.Map(rawArguments[m.Index]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps multiple positional raw call-site argument slices to named child-rule parameter seeds; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule that will receive the seeds when next entered.</param>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Pre-split argument slices. Must not be <c>null</c>.</param>");
        sb.AppendLine("    /// <param name=\"mappings\">One or more positional mappings.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when all mappings were applied; <c>false</c> when any mapping index is out of range (no seed is set for any mapping in that case).</returns>");
        sb.AppendLine("    /// <remarks>Seeds are rollback-safe when the managed execution-state mechanism is active. This is not ANTLR-compatible argument passing.</remarks>");
        sb.AppendLine("    private bool SetNextRuleParametersFromRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, global::System.Collections.Generic.IReadOnlyList<string> rawArguments, params global::Utils.Parser.Runtime.ParserRawArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(rawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (m.Index < 0 || m.Index >= rawArguments.Count) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            _frameManager?.SetPendingChildParameter(ruleName, m.ParameterName, m.Map(rawArguments[m.Index]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── Named raw argument helpers ──────────────────────────────────────────────────────────

        sb.AppendLine("    /// <summary>Splits raw call-site argument text into named top-level key–value pairs.</summary>");
        sb.AppendLine("    /// <param name=\"rawArguments\">Raw argument text; <c>null</c> returns an empty dictionary.</param>");
        sb.AppendLine("    /// <param name=\"separatorMode\">Which separator to recognise. Defaults to colon-or-equals.</param>");
        sb.AppendLine("    /// <returns>A dictionary of trimmed name–value pairs, or an empty dictionary when <paramref name=\"rawArguments\"/> is <c>null</c> or whitespace-only.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no value is evaluated, no parameter is bound. Separator inside nesting or quotes is ignored. Missing separator throws <see cref=\"global::System.FormatException\"/>.</remarks>");
        sb.AppendLine("    private static global::System.Collections.Generic.IReadOnlyDictionary<string, string> SplitNamedRawArgumentsTopLevel(string? rawArguments, global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode separatorMode = global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode.ColonOrEquals)");
        sb.AppendLine("    {");
        sb.AppendLine("        return rawArguments is null");
        sb.AppendLine("            ? new global::System.Collections.Generic.Dictionary<string, string>()");
        sb.AppendLine("            : global::Utils.Parser.Runtime.ParserRawNamedArgumentSplitter.SplitNamedTopLevel(rawArguments, separatorMode);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text from the most recent completed child rule call result into named key–value pairs.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the invocation frame to inspect.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name; returns <c>false</c> when mismatched or raw arguments absent.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the name–value dictionary when the helper returns <c>true</c>; otherwise an empty dictionary.</param>");
        sb.AppendLine("    /// <param name=\"separatorMode\">Which separator to recognise.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with parseable named arguments was found; <c>false</c> otherwise.</returns>");
        sb.AppendLine("    /// <remarks>Syntactic only: no value is evaluated, no parameter is bound.</remarks>");
        sb.AppendLine("    private static bool TrySplitLastRuleCallNamedRawArguments(ParserRuleLifecycleContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyDictionary<string, string> arguments, global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode separatorMode = global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode.ColonOrEquals)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        arguments = new global::System.Collections.Generic.Dictionary<string, string>();");
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments)) return false;");
        sb.AppendLine("        try { arguments = global::Utils.Parser.Runtime.ParserRawNamedArgumentSplitter.SplitNamedTopLevel(rawArguments!, separatorMode); return true; }");
        sb.AppendLine("        catch (global::System.FormatException) { arguments = new global::System.Collections.Generic.Dictionary<string, string>(); return false; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attempts to split the raw call-site argument text into named pairs; inline-action overload.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Inline-action context identifying the current parser action.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Expected rule name.</param>");
        sb.AppendLine("    /// <param name=\"arguments\">Receives the name–value dictionary when the helper returns <c>true</c>.</param>");
        sb.AppendLine("    /// <param name=\"separatorMode\">Which separator to recognise.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when a matching call result with parseable named arguments was found; <c>false</c> otherwise.</returns>");
        sb.AppendLine("    private bool TrySplitLastRuleCallNamedRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, out global::System.Collections.Generic.IReadOnlyDictionary<string, string> arguments, global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode separatorMode = global::Utils.Parser.Runtime.ParserRawNamedArgumentSeparatorMode.ColonOrEquals)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine();
        sb.AppendLine("        arguments = new global::System.Collections.Generic.Dictionary<string, string>();");
        sb.AppendLine("        if (!TryGetLastRuleCallRawArguments(context, ruleName, out string? rawArguments)) return false;");
        sb.AppendLine("        try { arguments = global::Utils.Parser.Runtime.ParserRawNamedArgumentSplitter.SplitNamedTopLevel(rawArguments!, separatorMode); return true; }");
        sb.AppendLine("        catch (global::System.FormatException) { arguments = new global::System.Collections.Generic.Dictionary<string, string>(); return false; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps named raw argument entries to child-rule parameter seeds using explicit caller-supplied mapper delegates.</summary>");
        sb.AppendLine("    /// <param name=\"context\">Lifecycle context carrying the caller invocation frame.</param>");
        sb.AppendLine("    /// <param name=\"ruleName\">Name of the child rule.</param>");
        sb.AppendLine("    /// <param name=\"namedRawArguments\">Named argument dictionary from <c>TrySplitLastRuleCallNamedRawArguments</c>.</param>");
        sb.AppendLine("    /// <param name=\"mappings\">One or more named mappings. Validated before any seed is applied.</param>");
        sb.AppendLine("    /// <returns><c>true</c> when all mappings were applied; <c>false</c> when any argument name is absent (no partial seeding).</returns>");
        sb.AppendLine("    /// <remarks>Duplicate ParameterName: last mapping wins. Mapper exceptions propagate. Null mapped values allowed.</remarks>");
        sb.AppendLine("    private static bool SetNextRuleParametersFromNamedRawArguments(ParserRuleLifecycleContext context, string ruleName, global::System.Collections.Generic.IReadOnlyDictionary<string, string> namedRawArguments, params global::Utils.Parser.Runtime.ParserRawNamedArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(namedRawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ArgumentName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (!namedRawArguments.ContainsKey(m.ArgumentName)) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            SetNextRuleParameter(context, ruleName, m.ParameterName, m.Map(namedRawArguments[m.ArgumentName]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maps named raw argument entries to child-rule parameter seeds; inline-action overload.</summary>");
        sb.AppendLine("    private bool SetNextRuleParametersFromNamedRawArguments(global::Utils.Parser.Runtime.ParserActionExecutionContext context, string ruleName, global::System.Collections.Generic.IReadOnlyDictionary<string, string> namedRawArguments, params global::Utils.Parser.Runtime.ParserRawNamedArgumentParameterMapping[] mappings)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ruleName);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(namedRawArguments);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(mappings);");
        sb.AppendLine();
        sb.AppendLine("        if (mappings.Length == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ParameterName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.ArgumentName);");
        sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(m.Map);");
        sb.AppendLine("            if (!namedRawArguments.ContainsKey(m.ArgumentName)) return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (var m in mappings)");
        sb.AppendLine("            _frameManager?.SetPendingChildParameter(ruleName, m.ParameterName, m.Map(namedRawArguments[m.ArgumentName]));");
        sb.AppendLine();
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
