using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Utils.Parser.Generators.Internal;

/// <summary>
/// Emits C# source code for a syntax colorization profile class.
/// </summary>
internal static class SyntaxColorizationEmitter
{
    /// <summary>
    /// Emits a syntax colorization class implementing <c>Utils.Parser.Runtime.ISyntaxColorisation</c>.
    /// </summary>
    /// <param name="descriptor">Parsed descriptor model.</param>
    /// <param name="namespaceName">Target namespace.</param>
    /// <param name="className">Generated class name.</param>
    /// <param name="sourceFileName">Descriptor source file name.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(
        SyntaxColorizationDescriptor descriptor,
        string namespaceName,
        string className,
        string sourceFileName)
    {
        var sb = new StringBuilder();

        var entries = descriptor.Entries
            .SelectMany(entry => entry.Rules.Select(rule => (Rule: rule, Classification: NormalizeClassification(entry.ClassificationName))))
            .GroupBy(item => item.Rule, StringComparer.OrdinalIgnoreCase)
            .Select(group => group.Last())
            .OrderBy(item => item.Rule, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        string[] fileExtensions = descriptor.FileExtensions
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(value => value, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        string[] stringSyntaxExtensions = descriptor.StringSyntaxExtensions
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(value => value, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Source: {sourceFileName}");
        sb.AppendLine("// This file was generated by Utils.Parser.Generators — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Utils.Parser.Runtime;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Syntax colorization profile generated from <c>{sourceFileName}</c>.</summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Utils.Parser.Generators\", \"0.1.0\")]");
        sb.AppendLine($"public sealed class {className} : ISyntaxColorisation");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, string> s_classificationByRule = new Dictionary<string, string>(global::System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");

        foreach (var entry in entries)
        {
            sb.AppendLine($"        [\"{Escape(entry.Rule)}\"] = \"{Escape(entry.Classification)}\",");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Gets the singleton colorization profile instance for <c>{className}</c>.</summary>");
        sb.AppendLine($"    public static {className} Instance {{ get; }} = new {className}();");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public IReadOnlyList<string> FileExtensions {{ get; }} = new string[] {{ {JoinStringLiterals(fileExtensions)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public IReadOnlyList<string> StringSyntaxExtensions {{ get; }} = new string[] {{ {JoinStringLiterals(stringSyntaxExtensions)} }};");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string? GetClassification(IEnumerable<string> rulePath)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (rulePath == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        foreach (string ruleName in rulePath.Reverse())");
        sb.AppendLine("        {");
        sb.AppendLine("            string? classification = GetClassification(ruleName);");
        sb.AppendLine("            if (classification != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                return classification;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string? GetClassification(string ruleName)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(ruleName))");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return s_classificationByRule.TryGetValue(ruleName, out string? classification) ? classification : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Maps descriptor classification aliases to Visual Studio standard names.
    /// </summary>
    /// <param name="classificationName">Raw descriptor classification name.</param>
    /// <returns>Visual Studio classification name.</returns>
    private static string NormalizeClassification(string classificationName)
    {
        if (classificationName.Equals("Keyword", StringComparison.OrdinalIgnoreCase))
        {
            return "Keyword";
        }

        if (classificationName.Equals("Number", StringComparison.OrdinalIgnoreCase))
        {
            return "Number";
        }

        if (classificationName.Equals("String", StringComparison.OrdinalIgnoreCase))
        {
            return "String";
        }

        if (classificationName.Equals("Operator", StringComparison.OrdinalIgnoreCase))
        {
            return "Operator";
        }

        if (classificationName.Equals("Raw text", StringComparison.OrdinalIgnoreCase) ||
            classificationName.Equals("Text", StringComparison.OrdinalIgnoreCase))
        {
            return "Plain Text";
        }

        return classificationName;
    }

    /// <summary>
    /// Escapes a value for embedding inside a C# verbatim string literal.
    /// Handles backslash, double-quote, and common control characters
    /// that would otherwise produce invalid or surprising C# source.
    /// </summary>
    /// <param name="value">Value to escape.</param>
    /// <returns>Escaped value safe for use inside a C# string literal.</returns>
    private static string Escape(string value) =>
        value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\0", "\\0");

    /// <summary>
    /// Joins string values as C# literals.
    /// </summary>
    /// <param name="values">Values to join.</param>
    /// <returns>Joined literals.</returns>
    private static string JoinStringLiterals(IEnumerable<string> values)
    {
        return string.Join(", ", values.Select(value => $"\"{Escape(value)}\""));
    }
}
