//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Mathematics {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberConverterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberConverterResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Mathematics.NumberConverterResources", typeof(NumberConverterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8"?&gt;
        ///&lt;xs:schema id="NumberConvertionConfiguration"
        ///    xmlns:xs="http://www.w3.org/2001/XMLSchema"
        ///    targetNamespace="Utils/NumberConvertionConfiguration.xsd"
        ///    xmlns="Utils/NumberConvertionConfiguration.xsd"
        ///    elementFormDefault="qualified"
        ///&gt;
        ///    &lt;xs:complexType name="DigitType"&gt;
        ///        &lt;xs:attribute name="digit"&gt;
        ///            &lt;xs:simpleType&gt;
        ///                &lt;xs:restriction base="xs:long"&gt;
        ///                    &lt;xs:totalDigits value="1"/&gt;
        ///                &lt;/xs:restriction&gt;
        ///            &lt;/xs:simpleType&gt;
        ///        &lt;/xs:attribute&gt;
        /// [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="صفر"
        ///        minus="سالب *"
        ///        decimalSeparator="فاصل"
        ///        fractionSeparator="على"
        ///        maxNumber="999999999"
        ///    &gt;
        ///        &lt;Culture&gt;AR&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="واحد" /&gt; [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_AR {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                groupSize="3"
        ///                separator=" "
        ///                groupSeparator=""
        ///                zero="null"
        ///                minus="minus *"
        ///                decimalSeparator="komma"
        ///                fractionSeparator="durch"
        ///        &gt;
        ///        &lt;Culture&gt;DE&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="ein" /&gt;
        ///                &lt;D [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_CA {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                groupSize="3"
        ///                separator=" "
        ///                groupSeparator=""
        ///                zero="null"
        ///                minus="minus *"
        ///                decimalSeparator="komma"
        ///                fractionSeparator="durch"
        ///        &gt;
        ///        &lt;Culture&gt;DE&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="ein" /&gt;
        ///                &lt;D [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_DE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="kpɔ"
        ///        minus="minus *"
        ///        decimalSeparator="kpɔ"
        ///        fractionSeparator="kple"
        ///    &gt;
        ///        &lt;Culture&gt;EE&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="deka" /&gt;
        ///                &lt;Digit digit="2" string="eve" /&gt;
        ///                &lt;Digit digit="3" string="eto" /&gt;
        /// [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_EE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="μηδέν"
        ///        minus="μείον *"
        ///        decimalSeparator="κόμμα"
        ///        fractionSeparator="διά"
        ///    &gt;
        ///        &lt;Culture&gt;EL&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="ένα" /&gt;
        ///                &lt;Digit digit="2" string="δύο" /&gt;
        ///                &lt;Digit digit="3" string="τρία" / [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_EL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                        groupSize="3"
        ///                        separator=" "
        ///                        groupSeparator="," 
        ///                        zero="zero"
        ///                        minus="minus *"
        ///                        decimalSeparator="point"
        ///                        fractionSeparator="over"
        ///        &gt;
        ///        &lt;Culture&gt;EN&lt;/Culture&gt;
        ///        &lt;Culture&gt;EN-uk&lt;/Culture&gt;
        ///        &lt;Culture&gt;EN-us&lt;/Culture&gt;
        /// [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_ES {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///                groupSize="3"
        ///                separator=" "
        ///                groupSeparator=""
        ///                zero="cero"
        ///                minus="menos *"
        ///                decimalSeparator="coma"
        ///                fractionSeparator="sobre"
        ///        &gt;
        ///        &lt;Culture&gt;ES&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="uno" /&gt;
        ///                &lt;Di [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_EN {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///                groupSize="3"
        ///                separator=" "
        ///                groupSeparator=""
        ///                zero="cero"
        ///                minus="menos *"
        ///                decimalSeparator="coma"
        ///                fractionSeparator="sobre"
        ///        &gt;
        ///        &lt;Culture&gt;ES&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="uno" /&gt;
        ///                &lt;Di [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_EU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="nolla"
        ///        minus="miinus *"
        ///        decimalSeparator="pilkku"
        ///        fractionSeparator="yli"
        ///        maxNumber="999999999"
        ///    &gt;
        ///        &lt;Culture&gt;FI&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="yk [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_FI {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                        groupSize="3"
        ///                        separator=" "
        ///                        groupSeparator=""
        ///                        zero="zéro"
        ///                        minus="moins *"
        ///                        decimalSeparator="virgule"
        ///                        fractionSeparator="sur"
        ///        &gt;
        ///        &lt;Culture&gt;FR-be&lt;/Culture&gt;
        ///        &lt;Culture&gt;FR-ch&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group leve [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_FR_be_ch {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FR-be-ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                        groupSize="3"
        ///                        separator=" "
        ///                        groupSeparator=""
        ///                        zero="zéro"
        ///                        minus="moins *"
        ///                        decimalSeparator="virgule"
        ///                        fractionSeparator="sur"
        ///        &gt;
        ///        &lt;Culture&gt;FR&lt;/Culture&gt;
        ///        &lt;Culture&gt;FR-fr&lt;/Culture&gt;
        ///        &lt;Culture&gt;FR-ca&lt;/Culture&gt;
        ///     [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_FR_fr_ca {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FR-fr-ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="אפס"
        ///        minus="מינוס *"
        ///        decimalSeparator="נקודה"
        ///        fractionSeparator="על"
        ///        maxNumber="999999999"
        ///    &gt;
        ///        &lt;Culture&gt;HE&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="אחד" /&gt; [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_HE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="शून्य"
        ///        minus="माइनस *"
        ///        decimalSeparator="दशमलव"
        ///        fractionSeparator="बटे"
        ///    &gt;
        ///        &lt;Culture&gt;HI&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="एक" /&gt;
        ///                &lt;Digit digi [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_HI {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.HI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                groupSize="3"
        ///                separator=" "
        ///                groupSeparator=""
        ///                zero="zero"
        ///                minus="meno *"
        ///                decimalSeparator="virgola"
        ///                fractionSeparator="su"
        ///        &gt;
        ///        &lt;Culture&gt;IT&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="uno" /&gt;
        ///                &lt;Digit digit="2" string="due" /&gt;
        ///                &lt;Digit digit="3" string="tre" / [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_GL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///        &lt;Language
        ///                groupSize="3"
        ///                separator=" "
        ///                groupSeparator=""
        ///                zero="zero"
        ///                minus="meno *"
        ///                decimalSeparator="virgola"
        ///                fractionSeparator="su"
        ///        &gt;
        ///        &lt;Culture&gt;IT&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="uno" /&gt;
        ///                &lt;Digit digit="2" string="due" /&gt;
        ///                &lt;Digit digit="3" string="tre" / [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_IT {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="零"
        ///        minus="マイナス *"
        ///        decimalSeparator="点"
        ///        fractionSeparator="割る"
        ///        maxNumber="999999999"
        ///    &gt;
        ///        &lt;Culture&gt;JA&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="一" /&gt;
        ///                &lt;Digit digit="2" string="二" /&gt;
        ///                &lt;Digit digit="3 [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_JA {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.JA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="영"
        ///        minus="마이너스 *"
        ///        decimalSeparator="점"
        ///        fractionSeparator="나누기"
        ///        maxNumber="999999999"
        ///    &gt;
        ///        &lt;Culture&gt;KO&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="일" /&gt;
        ///       [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_KO {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="nul"
        ///        minus="min *"
        ///        decimalSeparator="komma"
        ///        fractionSeparator="op"
        ///    &gt;
        ///        &lt;Culture&gt;NL&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="een" /&gt;
        ///                &lt;Digit digit="2 [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_NL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="zero"
        ///        minus="minus *"
        ///        decimalSeparator="przecinek"
        ///        fractionSeparator="przez"
        ///    &gt;
        ///        &lt;Culture&gt;PL&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="jeden" /&gt;
        ///                &lt;Di [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_PL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="zero"
        ///        minus="menos *"
        ///        decimalSeparator="vírgula"
        ///        fractionSeparator="sobre"
        ///    &gt;
        ///        &lt;Culture&gt;PT&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="um" /&gt;
        ///                &lt;Digit digit="2" string="dois" /&gt;
        ///                &lt;Digit digit="3" string="três [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_PT {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="ноль"
        ///        minus="минус *"
        ///        decimalSeparator="запятая"
        ///        fractionSeparator="на"
        ///    &gt;
        ///        &lt;Culture&gt;RU&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="один" /&gt;
        ///                &lt;Digit di [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_RU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="sero"
        ///        minus="minus *"
        ///        decimalSeparator="pojint"
        ///        fractionSeparator="ci"
        ///    &gt;
        ///        &lt;Culture&gt;WO&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="benn" /&gt;
        ///                &lt;Digit dig [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_WO {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.WO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="零"
        ///        minus="负 *"
        ///        decimalSeparator="点"
        ///        fractionSeparator="除以"
        ///        maxNumber="999999999"
        ///    &gt;
        ///        &lt;Culture&gt;ZH&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="一" /&gt;
        ///           [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_ZH {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version="1.0" encoding="utf-8" ?&gt;
        ///&lt;Numbers xmlns="Utils/NumberConvertionConfiguration.xsd"&gt;
        ///    &lt;Language
        ///        groupSize="3"
        ///        separator=" "
        ///        groupSeparator=""
        ///        zero="iqanda"
        ///        minus="minus *"
        ///        decimalSeparator="phuzu"
        ///        fractionSeparator="ngaphezu"
        ///    &gt;
        ///        &lt;Culture&gt;ZU&lt;/Culture&gt;
        ///        &lt;Groups&gt;
        ///            &lt;Group level="1"&gt;
        ///                &lt;Digit digit="0" string="" /&gt;
        ///                &lt;Digit digit="1" string="kunye" /&gt;
        ///                &lt;D [le reste de la chaîne a été tronqué]".
        /// </summary>
        internal static string NumberConvertionConfiguration_ZU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ZU", resourceCulture);
            }
        }
    }
}

