//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Mathematics {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberConverterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberConverterResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Mathematics.NumberConverterResources", typeof(NumberConverterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;NumberConvertionConfiguration&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    targetNamespace=&quot;Utils/NumberConvertionConfiguration.xsd&quot;
        ///    xmlns=&quot;Utils/NumberConvertionConfiguration.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///&gt;
        ///	&lt;xs:complexType name=&quot;DigitType&quot;&gt;
        ///		&lt;xs:attribute name=&quot;digit&quot;&gt;
        ///			&lt;xs:simpleType&gt;
        ///				&lt;xs:restriction base=&quot;xs:long&quot;&gt;
        ///					&lt;xs:totalDigits value=&quot;1&quot;/&gt;
        ///				&lt;/xs:restriction&gt;
        ///			&lt;/xs:simpleType&gt;
        ///		&lt;/xs:attribute&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NumberConvertionConfiguration {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Numbers xmlns=&quot;Utils/NumberConvertionConfiguration.xsd&quot;&gt;
        ///	&lt;Language
        ///		groupSize=&quot;3&quot;
        ///		separator=&quot; &quot;
        ///		groupSeparator=&quot;&quot;
        ///		zero=&quot;null&quot;
        ///		minus=&quot;minus *&quot;
        ///	&gt;
        ///		&lt;Culture&gt;DE&lt;/Culture&gt;
        ///		&lt;Groups&gt;
        ///			&lt;Group level=&quot;1&quot;&gt;
        ///				&lt;Digit digit=&quot;0&quot; string=&quot;&quot; /&gt;
        ///				&lt;Digit digit=&quot;1&quot; string=&quot;ein&quot; /&gt;
        ///				&lt;Digit digit=&quot;2&quot; string=&quot;zwei&quot; /&gt;
        ///				&lt;Digit digit=&quot;3&quot; string=&quot;drei&quot; /&gt;
        ///				&lt;Digit digit=&quot;4&quot; string=&quot;vier&quot; /&gt;
        ///				&lt;Digit digit=&quot;5&quot; string=&quot;fünf&quot; /&gt;
        ///				&lt;Digit digit=&quot;6 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NumberConvertionConfiguration_DE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Numbers xmlns=&quot;Utils/NumberConvertionConfiguration.xsd&quot;&gt;
        ///	&lt;Language
        ///		groupSize=&quot;3&quot;
        ///		separator=&quot; &quot;
        ///		groupSeparator=&quot;,&quot;
        ///		zero=&quot;zero&quot;
        ///		minus=&quot;minus *&quot;
        ///	&gt;
        ///		&lt;Culture&gt;EN&lt;/Culture&gt;
        ///		&lt;Culture&gt;EN-uk&lt;/Culture&gt;
        ///		&lt;Culture&gt;EN-us&lt;/Culture&gt;
        ///		&lt;Groups&gt;
        ///			&lt;Group level=&quot;1&quot;&gt;
        ///				&lt;Digit digit=&quot;0&quot; string=&quot;&quot;  /&gt;
        ///				&lt;Digit digit=&quot;1&quot; string=&quot;one&quot; /&gt;
        ///				&lt;Digit digit=&quot;2&quot; string=&quot;two&quot; /&gt;
        ///				&lt;Digit digit=&quot;3&quot; string=&quot;three&quot; /&gt;
        ///				&lt;Digit digit=&quot;4&quot; string=&quot;four&quot; /&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NumberConvertionConfiguration_EN {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Numbers xmlns=&quot;Utils/NumberConvertionConfiguration.xsd&quot;&gt;
        ///	&lt;Language
        ///		groupSize=&quot;3&quot;
        ///		separator=&quot; &quot;
        ///		groupSeparator=&quot;&quot;
        ///		zero=&quot;zéro&quot;
        ///		minus=&quot;moins *&quot;
        ///	&gt;
        ///		&lt;Culture&gt;FR-be&lt;/Culture&gt;
        ///		&lt;Culture&gt;FR-ch&lt;/Culture&gt;
        ///		&lt;Groups&gt;
        ///			&lt;Group level=&quot;1&quot;&gt;
        ///				&lt;Digit digit=&quot;0&quot; string=&quot;&quot; /&gt;
        ///				&lt;Digit digit=&quot;1&quot; string=&quot;et un&quot; /&gt;
        ///				&lt;Digit digit=&quot;2&quot; string=&quot;deux&quot; /&gt;
        ///				&lt;Digit digit=&quot;3&quot; string=&quot;trois&quot; /&gt;
        ///				&lt;Digit digit=&quot;4&quot; string=&quot;quatre&quot; /&gt;
        ///				&lt;Digit digit=&quot;5&quot; s [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NumberConvertionConfiguration_FR_be_ch {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration_FR_be_ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Numbers xmlns=&quot;Utils/NumberConvertionConfiguration.xsd&quot;&gt;
        ///	&lt;Language
        ///		groupSize=&quot;3&quot;
        ///		separator=&quot; &quot;
        ///		groupSeparator=&quot;&quot;
        ///		zero=&quot;zéro&quot;
        ///		minus=&quot;moins *&quot;
        ///	&gt;
        ///		&lt;Culture&gt;FR&lt;/Culture&gt;
        ///		&lt;Culture&gt;FR-fr&lt;/Culture&gt;
        ///		&lt;Culture&gt;FR-ca&lt;/Culture&gt;
        ///		&lt;Groups&gt;
        ///			&lt;Group level=&quot;1&quot;&gt;
        ///				&lt;Digit digit=&quot;0&quot; string=&quot;&quot; /&gt;
        ///				&lt;Digit digit=&quot;1&quot; string=&quot;et un&quot; /&gt;
        ///				&lt;Digit digit=&quot;2&quot; string=&quot;deux&quot; /&gt;
        ///				&lt;Digit digit=&quot;3&quot; string=&quot;trois&quot; /&gt;
        ///				&lt;Digit digit=&quot;4&quot; string=&quot;quatre&quot; / [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NumberConvertionConfiguration_FR_fr_ca {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration_FR_fr_ca", resourceCulture);
            }
        }
    }
}
