using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Immutable;
using System.Text;
using Utils.Parser.Diagnostics;
using Utils.Parser.Generators;

namespace UtilsTest.Parser;

/// <summary>
/// Verifies source-generator diagnostics for visible embedded-code constructs that are intentionally not executed.
/// </summary>
[TestClass]
public class Antlr4GrammarGeneratorDiagnosticsTests
{
    /// <summary>
    /// Ensures lexer actions are reported as unsupported generator execution constructs.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_LexerAction_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;
            start : A ;
            A : 'a' { OnLex(context); } ;
            """;

        var diagnostics = RunGenerator(grammar);
        var diagnostic = AssertSingleUnsupportedDiagnostic(diagnostics, "Lexer action");

        Assert.AreEqual(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning, diagnostic.Severity);
        StringAssert.Contains(diagnostic.GetMessage(), "not executed");
        AssertGeneratedSourceDoesNotContainLexerHook(grammar);
    }

    /// <summary>
    /// Ensures lexer predicates are reported as unsupported generator execution constructs.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_LexerPredicate_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;
            start : A ;
            A : { IsA(context) }? 'a' ;
            """;

        var diagnostic = AssertSingleUnsupportedDiagnostic(RunGenerator(grammar), "Lexer predicate");

        Assert.AreEqual(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning, diagnostic.Severity);
        StringAssert.Contains(diagnostic.GetMessage(), "lexer-state-aware");
    }

    /// <summary>
    /// Ensures unsupported grammar-level actions are reported as metadata-only generator constructs.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_GrammarAction_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;

            @footer {
                // metadata only
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostic = AssertSingleUnsupportedDiagnostic(RunGenerator(grammar), "Grammar @footer action");

        StringAssert.Contains(diagnostic.GetMessage(), "preserved as metadata only");
    }

    /// <summary>
    /// Ensures unscoped <c>@header</c> reports the compatibility warning for generated source injection.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_HeaderAction_ReportsSourceInjection()
    {
        const string grammar = """
            grammar P;

            @header {
                using System.Text;
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostics = RunGenerator(grammar);
        var diagnostic = AssertSingleHeaderInjectedDiagnostic(diagnostics, "Grammar @header action");
        string generatedSource = GetGeneratedSource(grammar);

        StringAssert.Contains(diagnostic.GetMessage(), "generated C# source");
        AssertNoUnsupportedDiagnostics(diagnostics);
        StringAssert.Contains(generatedSource, "// <auto-generated-parser-header>");
        StringAssert.Contains(generatedSource, "using System.Text;");
        StringAssert.Contains(generatedSource, "// </auto-generated-parser-header>");
    }

    /// <summary>
    /// Ensures <c>@parser::header</c> reports the compatibility warning for generated source injection.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_ParserHeaderAction_ReportsSourceInjection()
    {
        const string grammar = """
            grammar P;

            @parser::header {
                using System.Text;
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostics = RunGenerator(grammar);
        var diagnostic = AssertSingleHeaderInjectedDiagnostic(diagnostics, "Grammar @parser::header action");

        StringAssert.Contains(diagnostic.GetMessage(), "compatibility bridge only");
        AssertNoUnsupportedDiagnostics(diagnostics);
    }

    /// <summary>
    /// Ensures unscoped <c>@members</c> reports the compatibility warning for execution-context injection.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_MembersAction_ReportsExecutionContextInjection()
    {
        const string grammar = """
            grammar P;

            @members {
                private int Value;
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostic = AssertSingleMembersInjectedDiagnostic(RunGenerator(grammar), "Grammar @members action");

        StringAssert.Contains(diagnostic.GetMessage(), "per-parse execution context");
        Assert.IsFalse(diagnostic.GetMessage().Contains("not injected", StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Ensures <c>@parser::members</c> reports the compatibility warning for execution-context injection.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_ParserMembersAction_ReportsExecutionContextInjection()
    {
        const string grammar = """
            grammar P;

            @parser::members {
                private int Value;
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostic = AssertSingleMembersInjectedDiagnostic(RunGenerator(grammar), "Grammar @parser::members action");

        StringAssert.Contains(diagnostic.GetMessage(), "compatibility bridge");
    }

    /// <summary>
    /// Ensures unscoped <c>@members</c> in a parser-only grammar is injected into the parser execution context.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_ParserGrammarMembersAction_ReportsExecutionContextInjection()
    {
        const string grammar = """
            parser grammar P;

            @members {
                private int ParserState;
            }

            start : A ;
            """;

        var diagnostic = AssertSingleMembersInjectedDiagnostic(RunGenerator(grammar), "Grammar @members action");
        string generatedSource = GetGeneratedSource(grammar, "P.g4");

        StringAssert.Contains(diagnostic.GetMessage(), "per-parse execution context");
        StringAssert.Contains(generatedSource, "internal sealed partial class PExecutionContext");
        StringAssert.Contains(generatedSource, "private int ParserState;");
    }

    /// <summary>
    /// Ensures unscoped <c>@members</c> in a lexer-only grammar remains an unsupported lexer construct.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_LexerGrammarMembersAction_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            lexer grammar L;

            @members {
                private int LexerState;
            }

            A : 'a' ;
            """;

        var diagnostics = RunGenerator(grammar, "L.g4");
        var diagnostic = AssertSingleUnsupportedDiagnostic(diagnostics, "Grammar @members action");
        string generatedSource = GetGeneratedSource(grammar, "L.g4");

        StringAssert.Contains(diagnostic.GetMessage(), "metadata-only");
        AssertNoMembersInjectedDiagnostics(diagnostics);
        StringAssert.Contains(generatedSource, "internal sealed partial class LExecutionContext");
        Assert.IsFalse(generatedSource.Contains("private int LexerState;", StringComparison.Ordinal));
    }

    /// <summary>
    /// Ensures <c>@lexer::members</c> remains unsupported by the parser execution context.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_LexerMembersAction_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;

            @lexer::members {
                private int LexerState;
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostics = RunGenerator(grammar);
        var diagnostic = AssertSingleUnsupportedDiagnostic(diagnostics, "Grammar @lexer::members action");

        StringAssert.Contains(diagnostic.GetMessage(), "metadata-only");
        AssertNoMembersInjectedDiagnostics(diagnostics);
    }

    /// <summary>
    /// Ensures <c>@lexer::header</c> remains unsupported by generated parser source injection.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_LexerHeaderAction_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;

            @lexer::header {
                using System.Text;
            }

            start : A ;
            A : 'a' ;
            """;

        var diagnostics = RunGenerator(grammar);
        var diagnostic = AssertSingleUnsupportedDiagnostic(diagnostics, "Grammar @lexer::header action");
        string generatedSource = GetGeneratedSource(grammar);

        StringAssert.Contains(diagnostic.GetMessage(), "metadata-only");
        AssertNoHeaderInjectedDiagnostics(diagnostics);
        Assert.IsFalse(generatedSource.Contains("using System.Text;", StringComparison.Ordinal));
    }

    /// <summary>
    /// Ensures unscoped <c>@header</c> in a lexer-only grammar remains unsupported and is not injected as a parser header.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_LexerGrammarHeaderAction_ReportsUnsupportedEmbeddedCode()
    {
        const string grammar = """
            lexer grammar L;

            @header {
                using System.Text;
            }

            A : 'a' ;
            """;

        var diagnostics = RunGenerator(grammar, "L.g4");
        var diagnostic = AssertSingleUnsupportedDiagnostic(diagnostics, "Grammar @header action");
        string generatedSource = GetGeneratedSource(grammar, "L.g4");

        StringAssert.Contains(diagnostic.GetMessage(), "parser @header");
        AssertNoHeaderInjectedDiagnostics(diagnostics);
        Assert.IsFalse(generatedSource.Contains("using System.Text;", StringComparison.Ordinal));
    }

    /// <summary>
    /// Ensures rule <c>@init</c> lifecycle actions are not reported as unsupported embedded code now that they are generated.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_RuleInitAction_DoesNotReportUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;

            start
            @init { OnInit(context); }
                : A ;

            A : 'a' ;
            """;

        AssertNoUnsupportedDiagnostics(RunGenerator(grammar));
    }

    /// <summary>
    /// Ensures rule <c>@after</c> lifecycle actions are not reported as unsupported embedded code now that they are generated.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_RuleAfterAction_DoesNotReportUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;

            start
            @after { OnAfter(context); }
                : A ;

            A : 'a' ;
            """;

        AssertNoUnsupportedDiagnostics(RunGenerator(grammar));
    }

    /// <summary>
    /// Ensures supported parser semantic predicates are not reported as unsupported generator constructs.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_SupportedParserPredicate_DoesNotReportUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;
            start : { inputPosition == 0 }? A ;
            A : 'a' ;
            """;

        AssertNoUnsupportedDiagnostics(RunGenerator(grammar));
    }

    /// <summary>
    /// Ensures supported inline parser actions are not reported as unsupported generator constructs.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_SupportedInlineParserAction_DoesNotReportUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;
            start : { OnAction(context); } A ;
            A : 'a' ;
            """;

        AssertNoUnsupportedDiagnostics(RunGenerator(grammar));
    }

    /// <summary>
    /// Ensures invalid C# inside a supported generated predicate remains owned by Roslyn instead of the unsupported-construct diagnostic.
    /// </summary>
    [TestMethod]
    public void GeneratorDiagnostics_InvalidSupportedPredicateCode_DoesNotReportUnsupportedEmbeddedCode()
    {
        const string grammar = """
            grammar P;
            start : { return "not bool"; }? A ;
            A : 'a' ;
            """;

        AssertNoUnsupportedDiagnostics(RunGenerator(grammar));
    }

    /// <summary>
    /// Asserts that exactly one unsupported embedded-code diagnostic exists and that it describes the expected construct.
    /// </summary>
    /// <param name="diagnostics">Diagnostics emitted by the source generator.</param>
    /// <param name="expectedConstruct">Expected construct kind text.</param>
    /// <returns>The matching diagnostic.</returns>
    private static Diagnostic AssertSingleUnsupportedDiagnostic(ImmutableArray<Diagnostic> diagnostics, string expectedConstruct)
    {
        var matches = diagnostics
            .Where(static diagnostic => diagnostic.Id == ParserDiagnostics.EmbeddedCodeConstructNotExecutedByGenerator.Code)
            .ToArray();

        Assert.AreEqual(1, matches.Length, string.Join(Environment.NewLine, diagnostics));
        Assert.AreEqual(ParserDiagnostics.EmbeddedCodeConstructNotExecutedByGenerator.Code, matches[0].Id);
        StringAssert.Contains(matches[0].GetMessage(), expectedConstruct);
        StringAssert.Contains(matches[0].GetMessage(), "Supported generated C# embedded constructs");
        return matches[0];
    }

    /// <summary>
    /// Asserts that exactly one parser-members injection compatibility diagnostic exists and describes the expected construct.
    /// </summary>
    /// <param name="diagnostics">Diagnostics emitted by the source generator.</param>
    /// <param name="expectedConstruct">Expected construct kind text.</param>
    /// <returns>The matching diagnostic.</returns>
    private static Diagnostic AssertSingleMembersInjectedDiagnostic(ImmutableArray<Diagnostic> diagnostics, string expectedConstruct)
    {
        var matches = diagnostics
            .Where(static diagnostic => diagnostic.Id == ParserDiagnostics.EmbeddedMembersInjectedByGenerator.Code)
            .ToArray();

        Assert.AreEqual(1, matches.Length, string.Join(Environment.NewLine, diagnostics));
        Assert.AreEqual(ParserDiagnostics.EmbeddedMembersInjectedByGenerator.Code, matches[0].Id);
        Assert.AreEqual(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning, matches[0].Severity);
        StringAssert.Contains(matches[0].GetMessage(), expectedConstruct);
        return matches[0];
    }

    /// <summary>
    /// Asserts that exactly one parser-header injection compatibility diagnostic exists and describes the expected construct.
    /// </summary>
    /// <param name="diagnostics">Diagnostics emitted by the source generator.</param>
    /// <param name="expectedConstruct">Expected construct kind text.</param>
    /// <returns>The matching diagnostic.</returns>
    private static Diagnostic AssertSingleHeaderInjectedDiagnostic(ImmutableArray<Diagnostic> diagnostics, string expectedConstruct)
    {
        var matches = diagnostics
            .Where(static diagnostic => diagnostic.Id == ParserDiagnostics.EmbeddedHeaderInjectedByGenerator.Code)
            .ToArray();

        Assert.AreEqual(1, matches.Length, string.Join(Environment.NewLine, diagnostics));
        Assert.AreEqual(ParserDiagnostics.EmbeddedHeaderInjectedByGenerator.Code, matches[0].Id);
        Assert.AreEqual(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning, matches[0].Severity);
        StringAssert.Contains(matches[0].GetMessage(), expectedConstruct);
        return matches[0];
    }

    /// <summary>
    /// Asserts that no unsupported embedded-code source-generator diagnostics were emitted.
    /// </summary>
    /// <param name="diagnostics">Diagnostics emitted by the source generator.</param>
    private static void AssertNoUnsupportedDiagnostics(ImmutableArray<Diagnostic> diagnostics)
    {
        Assert.IsFalse(
            diagnostics.Any(static diagnostic => diagnostic.Id == ParserDiagnostics.EmbeddedCodeConstructNotExecutedByGenerator.Code),
            string.Join(Environment.NewLine, diagnostics));
    }

    /// <summary>
    /// Asserts that no parser-members injection compatibility diagnostics were emitted.
    /// </summary>
    /// <param name="diagnostics">Diagnostics emitted by the source generator.</param>
    private static void AssertNoMembersInjectedDiagnostics(ImmutableArray<Diagnostic> diagnostics)
    {
        Assert.IsFalse(
            diagnostics.Any(static diagnostic => diagnostic.Id == ParserDiagnostics.EmbeddedMembersInjectedByGenerator.Code),
            string.Join(Environment.NewLine, diagnostics));
    }

    /// <summary>
    /// Asserts that no parser-header injection compatibility diagnostics were emitted.
    /// </summary>
    /// <param name="diagnostics">Diagnostics emitted by the source generator.</param>
    private static void AssertNoHeaderInjectedDiagnostics(ImmutableArray<Diagnostic> diagnostics)
    {
        Assert.IsFalse(
            diagnostics.Any(static diagnostic => diagnostic.Id == ParserDiagnostics.EmbeddedHeaderInjectedByGenerator.Code),
            string.Join(Environment.NewLine, diagnostics));
    }

    /// <summary>
    /// Runs the ANTLR4 grammar source generator against an in-memory grammar file.
    /// </summary>
    /// <param name="grammar">ANTLR4 grammar source.</param>
    /// <param name="path">Virtual grammar file path used by the source generator.</param>
    /// <returns>Generator diagnostics.</returns>
    private static ImmutableArray<Diagnostic> RunGenerator(string grammar, string path = "P.g4")
    {
        var compilation = CSharpCompilation.Create(
            assemblyName: "GeneratorDiagnosticsTests",
            syntaxTrees: [CSharpSyntaxTree.ParseText("namespace Generated.Tests;", CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview))],
            references: [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [new Antlr4GrammarGenerator().AsSourceGenerator()],
            additionalTexts: [new InMemoryAdditionalText(path, grammar)],
            parseOptions: CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview));

        driver = driver.RunGenerators(compilation);
        return driver.GetRunResult().Diagnostics;
    }

    /// <summary>
    /// Runs the generator and returns the generated C# source for one in-memory grammar file.
    /// </summary>
    /// <param name="grammar">ANTLR4 grammar source.</param>
    /// <param name="path">Virtual grammar file path used by the source generator.</param>
    /// <returns>Generated source text.</returns>
    private static string GetGeneratedSource(string grammar, string path = "P.g4")
    {
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [new Antlr4GrammarGenerator().AsSourceGenerator()],
            additionalTexts: [new InMemoryAdditionalText(path, grammar)],
            parseOptions: CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Preview));

        var compilation = CSharpCompilation.Create("GeneratorDiagnosticsSourceTests");
        driver = driver.RunGenerators(compilation);
        return driver.GetRunResult().GeneratedTrees.Single().ToString();
    }

    /// <summary>
    /// Ensures generated source does not contain lexer hook helpers for lexer actions.
    /// </summary>
    /// <param name="grammar">ANTLR4 grammar source.</param>
    private static void AssertGeneratedSourceDoesNotContainLexerHook(string grammar)
    {
        string generatedSource = GetGeneratedSource(grammar);

        Assert.IsFalse(generatedSource.Contains("__Lexer", StringComparison.Ordinal));
        Assert.IsFalse(generatedSource.Contains("__Action_A", StringComparison.Ordinal));
    }

    /// <summary>
    /// In-memory additional file used to provide grammar text to the source generator.
    /// </summary>
    private sealed class InMemoryAdditionalText : AdditionalText
    {
        private readonly SourceText _text;

        /// <summary>
        /// Initializes an in-memory additional text file.
        /// </summary>
        /// <param name="path">Virtual file path.</param>
        /// <param name="text">File content.</param>
        public InMemoryAdditionalText(string path, string text)
        {
            Path = path;
            _text = SourceText.From(text, Encoding.UTF8);
        }

        /// <inheritdoc />
        public override string Path { get; }

        /// <inheritdoc />
        public override SourceText GetText(CancellationToken cancellationToken = default)
        {
            return _text;
        }
    }
}
