using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Reflection;
using System.Text;
using Utils.Parser.Diagnostics.EmbeddedCode;
using Utils.Parser.Generators.Internal;

namespace UtilsTest.Parser;

/// <summary>
/// Verifies centralized generated C# injection for transformed embedded-code fragments.
/// </summary>
[TestClass]
public sealed class CSharpEmbeddedCodeInjectorTests
{
    /// <summary>Ensures a single line can be injected without indentation.</summary>
    [TestMethod]
    public void InjectMethodBody_WhenSingleLineWithoutIndentation_WritesLine()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code("value++;"), 0);
        Assert.AreEqual($"value++;{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures multiple lines are preserved in order.</summary>
    [TestMethod]
    public void InjectMethodBody_WhenMultipleLines_WritesEachLine()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code("first();\nsecond();"), 0);
        Assert.AreEqual($"first();{Environment.NewLine}second();{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures supported newline forms are normalized through <see cref="StringBuilder.AppendLine()"/>.</summary>
    [DataTestMethod]
    [DataRow("a();\nb();")]
    [DataRow("a();\r\nb();")]
    [DataRow("a();\rb();")]
    public void InjectMethodBody_WhenNewlineFormsDiffer_NormalizesOutput(string source)
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code(source), 0);
        Assert.AreEqual($"a();{Environment.NewLine}b();{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures one indentation level means four spaces.</summary>
    [TestMethod]
    public void InjectMethodBody_WhenIndentedOneLevel_WritesFourSpaces()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code("value++;"), 1);
        Assert.AreEqual($"    value++;{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures method-body injection uses the requested method-body indentation.</summary>
    [TestMethod]
    public void InjectMethodBody_WhenMethodBodyIndented_WritesBodyIndentation()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code("value++;"), 2);
        Assert.AreEqual($"        value++;{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures interior empty lines remain present and indented like existing generated output.</summary>
    [TestMethod]
    public void InjectMethodBody_WhenEmptyLinesArePresent_PreservesIndentedEmptyLines()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code("a();\n\nb();"), 1);
        Assert.AreEqual($"    a();{Environment.NewLine}    {Environment.NewLine}    b();{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures empty transformed text emits no embedded-code body lines.</summary>
    [TestMethod]
    public void InjectMethodBody_WhenTextIsEmpty_WritesNothing()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectMethodBody(Code(""), 1);
        Assert.AreEqual(string.Empty, builder.ToString());
    }

    /// <summary>Ensures region markers surround transformed code.</summary>
    [TestMethod]
    public void InjectRegion_WhenParserHeader_WritesMarkers()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectRegion(Code("using System;"), CSharpEmbeddedCodeRegion.ParserHeader);
        string expected = $"// <auto-generated-parser-header>{Environment.NewLine}using System;{Environment.NewLine}// </auto-generated-parser-header>{Environment.NewLine}{Environment.NewLine}";
        Assert.AreEqual(expected, builder.ToString());
    }

    /// <summary>Ensures known descriptors explicitly control trailing blank lines.</summary>
    [TestMethod]
    public void RegionDescriptors_WhenKnownRegions_AreExplicitAboutTrailingBlankLine()
    {
        Assert.IsTrue(CSharpEmbeddedCodeRegionDescriptor.For(CSharpEmbeddedCodeRegion.ParserHeader).AppendTrailingBlankLine);
        Assert.IsTrue(CSharpEmbeddedCodeRegionDescriptor.For(CSharpEmbeddedCodeRegion.LexerMembers).AppendTrailingBlankLine);
    }

    /// <summary>Ensures predicate expressions are returned as expressions.</summary>
    [TestMethod]
    public void InjectReturnExpression_WhenPredicateExpression_WritesReturnStatement()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectReturnExpression(Code("context.InputPosition == 0"), 2);
        Assert.AreEqual($"        return context.InputPosition == 0;{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures action blocks are injected without a generated return wrapper.</summary>
    [TestMethod]
    public void InjectCompleteFragment_WhenActionBlock_WritesStatementsOnly()
    {
        var builder = new StringBuilder();
        new CSharpEmbeddedCodeInjector(builder).InjectCompleteFragment(Code("value++;\nreturn true;"), 2);
        Assert.AreEqual($"        value++;{Environment.NewLine}        return true;{Environment.NewLine}", builder.ToString());
    }

    /// <summary>Ensures injector APIs cannot receive raw embedded code or string code bodies.</summary>
    [TestMethod]
    public void InjectionApi_WhenReflected_DoesNotAcceptRawEmbeddedCodeOrStringCodeParameter()
    {
        MethodInfo[] methods = typeof(CSharpEmbeddedCodeInjector)
            .GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
            .Where(static method => method.DeclaringType == typeof(CSharpEmbeddedCodeInjector) && !method.IsPrivate)
            .ToArray();

        foreach (MethodInfo method in methods.Where(static method => method.Name.StartsWith("Inject", StringComparison.Ordinal)))
        {
            ParameterInfo[] parameters = method.GetParameters();
            Assert.IsFalse(parameters.Any(static parameter => parameter.ParameterType == typeof(RawEmbeddedCode)), method.ToString());
            Assert.IsFalse(parameters.Any(static parameter => parameter.ParameterType == typeof(string) && string.Equals(parameter.Name, "code", StringComparison.OrdinalIgnoreCase)), method.ToString());
            Assert.IsTrue(parameters.Any(static parameter => parameter.ParameterType == typeof(TransformedEmbeddedCode)), method.ToString());
        }
    }

    /// <summary>Creates transformed embedded code through the central transformation boundary.</summary>
    /// <param name="text">Text to wrap as transformed embedded code.</param>
    /// <returns>A transformed embedded-code instance.</returns>
    private static TransformedEmbeddedCode Code(string text)
    {
        return ParserEmbeddedCodeTransformationService.TransformOrThrow(
            NoOpParserEmbeddedCodeTransformer.Instance,
            new RawEmbeddedCode(text),
            new ParserEmbeddedCodeTransformationContext { Location = ParserEmbeddedCodeLocation.InlineAction, GrammarName = "P" },
            new ParserEmbeddedCodeTransformationFailureContext { Path = ParserEmbeddedCodeTransformationPath.GeneratedCodeEmission, Location = ParserEmbeddedCodeLocation.InlineAction, GrammarName = "P" });
    }
}
