using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Numerics;
using Utils.NumberToString;

namespace UtilsTest.NumberToString;

/// <summary>
/// NTS-23 guards for the Ewe large scales. akpe stays a static name; every higher scale is generated by the
/// Conway-Wechsler short scale inherited from SCALE-SHORT, spelled prefix + "li" + "ɔn". miliɔn, biliɔn and
/// triliɔn are sourced linguistic anchors; quadriliɔn and above are a project-defined productive
/// continuation, so their tests check the mechanism, not individually attested Ewe forms.
/// </summary>
[TestClass]
public class NumberToStringNts23Tests
{
    /// <summary>Gets the Ewe converter.</summary>
    private static NumberToStringConverter Ewe => NumberToStringConverter.GetConverter("EE");

    /// <summary>Gets the shared short-scale base configuration.</summary>
    private static NumberToStringConverter ShortScale => NumberToStringConverter.GetConverter("SCALE-SHORT");

    /// <summary>Returns 10 raised to <paramref name="exponent"/>.</summary>
    private static BigInteger Pow10(int exponent) => BigInteger.Pow(10, exponent);

    /// <summary>Converts a cardinal.</summary>
    private static string C(BigInteger value) => Ewe.Convert(value);

    /// <summary>
    /// The SCALE-SHORT prefix tables with groupSeparator "li" and suffix "ɔn" spell the Ewe anchors, with no
    /// index offset: the two static names (empty, akpe) are followed by Conway n = 1 at scale 2.
    /// </summary>
    [TestMethod]
    public void ConwayTablesWithLiOnSuffix_SpellTheEweScales()
    {
        var conway = ShortScale.Scale;
        var scale = new NumberScale(
            ["", "akpe"], ["ɔn"], startIndex: 0, groupSeparator: "li",
            scale0Prefixes: conway.Scale0Prefixes, unitsPrefixes: conway.UnitsPrefixes,
            tensPrefixes: conway.TensPrefixes, hundredsPrefixes: conway.HundredsPrefixes);

        Assert.AreEqual("akpe", scale.GetScaleName(1));
        Assert.AreEqual("miliɔn", scale.GetScaleName(2));
        Assert.AreEqual("biliɔn", scale.GetScaleName(3));
        Assert.AreEqual("triliɔn", scale.GetScaleName(4));
        Assert.AreEqual("quadriliɔn", scale.GetScaleName(5));
        Assert.AreEqual("quintiliɔn", scale.GetScaleName(6));
    }

    /// <summary>The configured Ewe scale names every index from the inherited Conway tables.</summary>
    [TestMethod]
    public void Ewe_ScaleNames_FollowConwayWechsler()
    {
        var scale = Ewe.Scale;
        Assert.AreEqual(0, scale.StartIndex);
        string[] expected =
        [
            "", "akpe", "miliɔn", "biliɔn", "triliɔn", "quadriliɔn", "quintiliɔn", "sextiliɔn",
            "septiliɔn", "octiliɔn", "noniliɔn", "deciliɔn",
        ];
        for (int index = 0; index < expected.Length; index++)
            Assert.AreEqual(expected[index], scale.GetScaleName(index), $"scale {index}");

        // Higher names follow the shared strict Conway-Wechsler construction of SCALE-SHORT (NTS-24), with the Ewe
        // junction "li" and suffix "ɔn": sedeciliɔn is the intended Conway form, the final vowel of a group becomes i
        // (trigintiliɔn), and each three-digit group above the 999th restarts from Scale0Prefixes (miliniliɔn).
        Assert.AreEqual("undeciliɔn", scale.GetScaleName(12));
        Assert.AreEqual("duodeciliɔn", scale.GetScaleName(13));
        Assert.AreEqual("sedeciliɔn", scale.GetScaleName(17));
        Assert.AreEqual("vigintiliɔn", scale.GetScaleName(21));
        Assert.AreEqual("trigintiliɔn", scale.GetScaleName(31));
        Assert.AreEqual("centiliɔn", scale.GetScaleName(101));
        Assert.AreEqual("miliniliɔn", scale.GetScaleName(1001));
        Assert.AreEqual("milimiliɔn", scale.GetScaleName(1002));
        Assert.AreEqual("miliniliniliɔn", scale.GetScaleName(1_000_001));
        Assert.AreEqual("milinilitriliɔn", scale.GetScaleName(1_000_004));
    }

    /// <summary>The generated scale is unbounded, so the domain has no maximum, like the other SCALE-SHORT languages.</summary>
    [TestMethod]
    public void Ewe_Domain_IsUnbounded()
    {
        var converter = Ewe;
        Assert.IsTrue(converter.Scale.IsUnbounded);
        Assert.IsTrue(converter.Scale.CanNameGroup(3));
        Assert.IsTrue(converter.Scale.CanNameGroup(1000));
        Assert.IsNull(converter.MaxNumber);
        Assert.AreEqual(ShortScale.MaxNumber, converter.MaxNumber);
    }

    /// <summary>The sourced anchors miliɔn, biliɔn and triliɔn (CLDR compact patterns) take the multiplier after the noun.</summary>
    [TestMethod]
    public void Ewe_SourcedAnchors()
    {
        Assert.AreEqual("akpe ɖeka", C(1_000));
        Assert.AreEqual("miliɔn ɖeka", C(Pow10(6)));
        Assert.AreEqual("biliɔn ɖeka", C(Pow10(9)));
        Assert.AreEqual("triliɔn ɖeka", C(Pow10(12)));
    }

    /// <summary>quadriliɔn and above: project-defined productive Conway-Wechsler extrapolation.</summary>
    [TestMethod]
    public void Ewe_ProductiveConwayContinuation()
    {
        Assert.AreEqual("quadriliɔn ɖeka", C(Pow10(15)));
        Assert.AreEqual("quintiliɔn ɖeka", C(Pow10(18)));
        Assert.AreEqual("sextiliɔn ɖeka", C(Pow10(21)));
        Assert.AreEqual("septiliɔn ɖeka", C(Pow10(24)));
        Assert.AreEqual("noniliɔn ɖeka", C(Pow10(30)));
        Assert.AreEqual("deciliɔn ɖeka", C(Pow10(33)));
    }

    /// <summary>The multiplier is the standalone cardinal placed after the scale noun.</summary>
    [TestMethod]
    public void Ewe_Multipliers_FollowTheScaleNoun()
    {
        Assert.AreEqual("miliɔn eve", C(2 * Pow10(6)));
        Assert.AreEqual("biliɔn blaeve vɔ ɖekɛ", C(21 * Pow10(9)));
        Assert.AreEqual("triliɔn alafa eve", C(200 * Pow10(12)));
        Assert.AreEqual("quadriliɔn alafa asieke blaasieke vɔ asieke", C(999 * Pow10(15)));
        Assert.AreEqual("minus biliɔn ɖeka", C(-Pow10(9)));

        // Every multiplier 1–999 of every opened scale is the standalone cardinal of the multiplier.
        var failures = new List<string>();
        string[] nouns = ["biliɔn", "triliɔn", "quadriliɔn", "quintiliɔn"];
        for (int scale = 3; scale <= 6; scale++)
            for (int multiplier = 1; multiplier <= 999; multiplier++)
            {
                string expected = nouns[scale - 3] + " " + C(multiplier);
                string actual = C(multiplier * Pow10(3 * scale));
                if (actual != expected) failures.Add($"{multiplier}e{3 * scale}: expected '{expected}', got '{actual}'");
            }
        Assert.AreEqual(0, failures.Count, string.Join(Environment.NewLine, failures));
    }

    /// <summary>Lower groups join like the thousands: "kple" before a group below 100, a plain space otherwise.</summary>
    [TestMethod]
    public void Ewe_MultiScaleCompositions()
    {
        Assert.AreEqual("biliɔn ɖeka kple miliɔn ɖeka", C(1_001_000_000));
        Assert.AreEqual("biliɔn ɖeka kple akpe ɖeka", C(1_000_001_000));
        Assert.AreEqual("biliɔn ɖeka kple ɖeka", C(1_000_000_001));
        Assert.AreEqual("triliɔn ɖeka kple biliɔn ɖeka", C(1_001_000_000_000));
        Assert.AreEqual("triliɔn ɖeka kple miliɔn ɖeka", C(1_000_001_000_000));
        Assert.AreEqual("triliɔn ɖeka kple akpe ɖeka", C(1_000_000_001_000));
        Assert.AreEqual("triliɔn ɖeka kple ɖeka", C(1_000_000_000_001));
        Assert.AreEqual("biliɔn eve miliɔn alafa ɖeka", C(2_100_000_000));
        Assert.AreEqual(
            "quadriliɔn ɖeka kple triliɔn eve biliɔn alafa etɔ̃ kple miliɔn ene kple akpe blaatɔ̃ alafa ade",
            C(1_002_300_004_050_600));
        Assert.AreEqual(
            "quadriliɔn alafa ɖeka blaeve vɔ etɔ̃ triliɔn alafa ene blaatɔ̃ vɔ ade biliɔn alafa adre blaenyi vɔ asieke " +
            "kple miliɔn ewo kple akpe wuiɖekɛ alafa ɖeka blaeve vɔ eve",
            C(123_456_789_010_011_122));
    }

    /// <summary>Ordinals add -lia to the last numeral element; the scale noun is never ordinalized.</summary>
    [TestMethod]
    public void Ewe_Ordinals_SuffixTheLastNumeral()
    {
        var converter = Ewe;
        Assert.AreEqual("miliɔn ɖekalia", converter.ConvertOrdinal(1_000_000));
        Assert.AreEqual("biliɔn ɖekalia", converter.ConvertOrdinal(1_000_000_000));
        Assert.AreEqual("triliɔn ɖekalia", converter.ConvertOrdinal(1_000_000_000_000));
        Assert.AreEqual("quadriliɔn ɖekalia", converter.ConvertOrdinal(1_000_000_000_000_000));
        Assert.AreEqual("biliɔn blaeve vɔ ɖekɛlia", converter.ConvertOrdinal(21_000_000_000));
        Assert.AreEqual("triliɔn ɖeka kple ɖekalia", converter.ConvertOrdinal(1_000_000_000_001));

        var failures = new List<string>();
        foreach (long number in new long[] { 2_000_000_000, 999_000_000_000, 1_001_000_000, 5_000_000_000_000_000, 1_002_300_004_050_600 })
        {
            string ordinal = converter.ConvertOrdinal(number);
            if (ordinal != C(number) + "lia" || ordinal.Contains("liɔnlia", StringComparison.Ordinal))
                failures.Add($"{number}: '{ordinal}'");
        }
        Assert.AreEqual(0, failures.Count, string.Join(Environment.NewLine, failures));
    }

    /// <summary>Very large BigInteger values convert without overflow; ordinals keep the engine-wide long limit.</summary>
    [TestMethod]
    public void Ewe_VeryLargeBigIntegers()
    {
        var converter = Ewe;
        Assert.AreEqual("quintiliɔn ɖeka", converter.Convert(Pow10(18)));
        Assert.AreEqual("vigintiliɔn ɖeka", converter.Convert(Pow10(63)));
        Assert.AreEqual("trigintiliɔn ɖeka", converter.Convert(Pow10(93)));
        Assert.AreEqual("centiliɔn ɖeka", converter.Convert(Pow10(303)));
        Assert.AreEqual("centiliɔn eve kple noniliɔn ɖeka kple ɖeka", converter.Convert(2 * Pow10(303) + Pow10(30) + 1));
        Assert.AreEqual("minus centiliɔn ɖeka", converter.Convert(-Pow10(303)));

        Assert.AreEqual("quintiliɔn ɖekalia", converter.ConvertOrdinal(Pow10(18)));
        Assert.AreEqual("quintiliɔn enyi kple ɖekalia", converter.ConvertOrdinal(8 * Pow10(18) + 1));
        // Ordinal conversion is limited to the long range for every language, independently of the scale.
        Assert.Throws<ArgumentOutOfRangeException>(() => converter.ConvertOrdinal(Pow10(21)));
    }

    /// <summary>akpe akpe is not produced: the modern scale names are canonical, with no traditional variant.</summary>
    [TestMethod]
    public void Ewe_AkpeAkpe_IsNotProduced()
    {
        Assert.IsFalse(C(Pow10(6)).Contains("akpe akpe", StringComparison.Ordinal));
        Assert.IsFalse(C(Pow10(9)).Contains("miliɔn akpe", StringComparison.Ordinal));
        Assert.AreEqual(0, Ewe.VariantDimensions.Count);
    }
}
