//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberConverterResources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberConverterResources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Utils.NumberConverterResources", typeof(NumberConverterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string NumberConvertionConfiguration {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration", resourceCulture);
            }
        internal static string NumberConvertionConfiguration_SCALE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.SCALE", resourceCulture);
            }
        internal static string NumberConvertionConfiguration_AR {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.AR", resourceCulture);
            }
        }
        internal static string NumberConvertionConfiguration_CS {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.CS", resourceCulture);
            }
        internal static string NumberConvertionConfiguration_SK {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.SK", resourceCulture);
            }
        internal static string NumberConvertionConfiguration_DE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.DE", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_DE_ch {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.DE-ch", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_DA {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.DA", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_EE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EE", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_EL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EL", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_EN {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EN", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_EN_GB {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EN-GB", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_ES {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ES", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_BG {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.BG", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_CA {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.CA", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_CA_valencia {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.CA-valencia", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_EU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.EU", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_FA {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FA", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_GL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.GL", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_FI {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FI", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_FR_be {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FR-be", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_FR_ch {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FR-ch", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_FR_fr_ca {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.FR-fr-ca", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_HE {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.HE", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_HR {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.HR", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_HU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.HU", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_HI {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.HI", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_ID {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ID", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_MS {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.MS", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_IT {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.IT", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_JA {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.JA", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_KO {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.KO", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_NL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.NL", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_NO {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.NO", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_PL {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.PL", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_PT {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.PT", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_RO {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.RO", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_RU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.RU", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_SV {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.SV", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_SW {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.SW", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_TR {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.TR", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_UK {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.UK", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_VN {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.VN", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_WO {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.WO", resourceCulture);
            }
        }

        internal static string NumberConvertionConfiguration_ZH {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ZH", resourceCulture);
            }
        internal static string NumberConvertionConfiguration_ZU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ZU", resourceCulture);
            }
        }
    }
}
        ///            &lt;Group level=&quot;1&quot;&gt;
        ///                &lt;Digit digit=&quot;0&quot; string=&quot;&quot; /&gt;
        ///                &lt;Digit digit=&quot;1&quot; string=&quot;kunye&quot; /&gt;
        ///                &lt;D [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NumberConvertionConfiguration_ZU {
            get {
                return ResourceManager.GetString("NumberConvertionConfiguration.ZU", resourceCulture);
            }
        }
    }
}
