<#
.SYNOPSIS
Generates and self-verifies the immutable release-candidate artifact manifest.
#>
[CmdletBinding()]
param([string] $ArtifactsPath = "artifacts", [switch] $RequireCrossPlatformValidation)
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.IO.Compression.FileSystem
. (Join-Path $PSScriptRoot 'Release.Common.ps1')
$repoRoot=Split-Path -Parent $PSScriptRoot;$source=Get-ProductTrainManifest $repoRoot;$root=Resolve-RepositoryPath $repoRoot $ArtifactsPath;$packageRoot=Join-Path $root 'packages'
$graph=Get-Content (Join-Path $root 'reports/package-graph.json') -Raw|ConvertFrom-Json
$inspection=Get-Content (Join-Path $root 'reports/package-inspection.json') -Raw|ConvertFrom-Json
$api=Get-Content (Join-Path $root 'reports/public-api-comparison.json') -Raw|ConvertFrom-Json
$warnings=Get-Content (Join-Path $root 'reports/warnings.json') -Raw|ConvertFrom-Json
$sourcelink=Get-Content (Join-Path $root 'reports/sourcelink.json') -Raw|ConvertFrom-Json
$repro=Get-Content (Join-Path $root 'reports/reproducibility-report.json') -Raw|ConvertFrom-Json
$acceptance=Get-Content (Join-Path $root 'reports/packaged-acceptance.json') -Raw|ConvertFrom-Json
$platformValidationPath=Join-Path $root 'reports/cross-platform-validation.json'
$platformValidation=if (Test-Path -LiteralPath $platformValidationPath) { Get-Content $platformValidationPath -Raw|ConvertFrom-Json } else { $null }
if ($RequireCrossPlatformValidation -and ($null -eq $platformValidation -or -not $platformValidation.ubuntu.passed -or -not $platformValidation.windows.passed)) { throw 'Cross-platform candidate validation did not pass.' }
$packages=@()
foreach($definition in $source.packages){$nupkg="$($definition.packageId).$($source.version).nupkg";$snupkg="$($definition.packageId).$($source.version).snupkg";$nupkgPath=Join-Path $packageRoot $nupkg;$snupkgPath=Join-Path $packageRoot $snupkg;if(-not(Test-Path $nupkgPath)-or -not (Test-Path $snupkgPath)){throw "$($definition.packageId): candidate artifacts missing."};$zip=[IO.Compression.ZipFile]::OpenRead($nupkgPath);try{$assemblies=@($zip.Entries|Where-Object FullName -like '*.dll'|ForEach-Object{$stream=$_.Open();$sha=[Security.Cryptography.SHA256]::Create();try{[ordered]@{path=$_.FullName;sha256=[Convert]::ToHexString($sha.ComputeHash($stream)).ToLowerInvariant();version='2.0.0.0'}}finally{$sha.Dispose();$stream.Dispose()}})}finally{$zip.Dispose()};$acceptanceEntry=$acceptance.packages|Where-Object packageId -eq $definition.packageId;$packages += [ordered]@{packageId=$definition.packageId;version=[string]$source.version;kind=$definition.kind;project=$definition.project;targetFrameworks=@($definition.targetFrameworks);dependencies=@($graph.edges|Where-Object from -eq $definition.packageId);nupkg=[ordered]@{file=$nupkg;sha256=(Get-FileHash $nupkgPath -Algorithm SHA256).Hash.ToLowerInvariant()};snupkg=[ordered]@{file=$snupkg;sha256=(Get-FileHash $snupkgPath -Algorithm SHA256).Hash.ToLowerInvariant()};assemblies=$assemblies;platformSupport=@($definition.platforms);acceptanceProfile=$definition.acceptanceProfile;acceptanceResult=if($acceptance.passed -and $acceptanceEntry.restored -and $acceptanceEntry.compiled){'passed'}else{'failed'};apiCompatibilityResult=($api.packages|Where-Object packageId -eq $definition.packageId).result;warningsResult=if(($warnings.packages|Where-Object packageId -eq $definition.packageId).passed){'passed'}else{'failed'};sourceLinkResult=if(($sourcelink.packages|Where-Object packageId -eq $definition.packageId).passed){'passed'}else{'failed'};reproducibilityResult=@($repro.artifacts|Where-Object packageId -eq $definition.packageId|Select-Object -ExpandProperty result -Unique)}}
$manifest=[ordered]@{productTrain=[string]$source.productTrain;version=[string]$source.version;repository=[string]$source.repository;commit=(&git -C $repoRoot rev-parse HEAD).Trim();platformValidation=$platformValidation;publicationOrder=@($graph.publicationOrder);packages=$packages}
$path=Join-Path $root 'manifests/release-candidate-manifest.json';Write-ReleaseJson $manifest $path
$roundTrip=Get-Content $path -Raw|ConvertFrom-Json;if($roundTrip.packages.Count -ne $source.packages.Count -or @($roundTrip.packages|Where-Object version -ne $roundTrip.version) -or @($roundTrip.packages|Where-Object acceptanceResult -ne 'passed') -or @($roundTrip.packages|Where-Object warningsResult -ne 'passed') -or @($roundTrip.packages|Where-Object sourceLinkResult -ne 'passed') -or @($roundTrip.packages|Where-Object { $_.apiCompatibilityResult -notin @('compatible','accepted-major-version-breaks','baseline-created') -or @($_.reproducibilityResult|Where-Object {$_ -notin @('bit-identical','logically-identical-after-zip-normalization')}) })){throw 'Candidate manifest self-validation failed.'};if((Compare-Object ($roundTrip.publicationOrder|Sort-Object) ($source.packages.packageId|Sort-Object)) -or ($roundTrip.publicationOrder|Sort-Object -Unique).Count -ne $source.packages.Count){throw 'Candidate publication order is incomplete, duplicated, or unknown.'};foreach($p in $roundTrip.packages){foreach($artifact in @($p.nupkg,$p.snupkg)){if((Get-FileHash (Join-Path $packageRoot $artifact.file) -Algorithm SHA256).Hash.ToLowerInvariant() -ne $artifact.sha256){throw "$($p.packageId): candidate manifest hash mismatch."}}}
Write-Host "Manifest: $path self-validation passed."
