using System;
using System.Data;
using System.Data.Common;
using System.Runtime.CompilerServices;
using Utils.Data.Sql;

namespace Utils.Data;

/// <summary>
/// Provides factory methods to create SQL commands and compile SQL queries using configured syntax options.
/// </summary>
public sealed class SqlCommandFactory
{
    /// <summary>
    /// Stores the syntax options applied to created interpolators and compiled queries.
    /// </summary>
    private readonly SqlSyntaxOptions syntaxOptions;

    /// <summary>
    /// Initializes a new instance of the <see cref="SqlCommandFactory"/> class.
    /// </summary>
    /// <param name="syntaxOptions">Syntax options controlling parameter and identifier prefixes.</param>
    public SqlCommandFactory(SqlSyntaxOptions? syntaxOptions = null)
    {
        this.syntaxOptions = syntaxOptions ?? SqlSyntaxOptions.Default;
    }

    /// <summary>
    /// Gets the syntax options applied by the factory.
    /// </summary>
    public SqlSyntaxOptions SyntaxOptions => syntaxOptions;

    /// <summary>
    /// Compiles the provided SQL text using the configured syntax options.
    /// </summary>
    /// <param name="sql">SQL string to parse.</param>
    /// <returns>A parsed representation of the SQL statement.</returns>
    public SqlQuery CompileQuery(string sql) => SqlQueryAnalyzer.Parse(sql, syntaxOptions);

    /// <summary>
    /// Sets the command text from the interpolated builder and returns the underlying command.
    /// </summary>
    /// <param name="interpolator">Interpolator that contains the built command text.</param>
    /// <returns>The command generated by the interpolator.</returns>
    internal static IDbCommand FinalizeCommand(CommandInterpolator interpolator)
    {
        IDbCommand command = interpolator.DbCommand;
        command.CommandText = interpolator.ToString();
        return command;
    }

    /// <summary>
    /// Interpolated string handler that builds SQL commands using the factory's syntax options.
    /// </summary>
    [InterpolatedStringHandler]
    public ref struct CommandInterpolator
    {
        /// <summary>
        /// Underlying interpolator used to build the SQL and parameters.
        /// </summary>
        private SqlBuilderInterpolator interpolator;

        /// <summary>
        /// Initializes a new instance of the <see cref="CommandInterpolator"/> struct.
        /// </summary>
        /// <param name="literalLength">Provided by the compiler to optimize the size of the string builder.</param>
        /// <param name="formattedCount">Number of formatted placeholders in the interpolation.</param>
        /// <param name="factory">Factory providing the syntax options to apply.</param>
        /// <param name="dbConnection">Connection used to create the underlying command.</param>
        public CommandInterpolator(int literalLength, int formattedCount, SqlCommandFactory factory, DbConnection dbConnection)
            : this(literalLength, formattedCount, factory, (IDbConnection)dbConnection)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommandInterpolator"/> struct.
        /// </summary>
        /// <param name="literalLength">Provided by the compiler to optimize the size of the string builder.</param>
        /// <param name="formattedCount">Number of formatted placeholders in the interpolation.</param>
        /// <param name="factory">Factory providing the syntax options to apply.</param>
        /// <param name="dbConnection">Connection used to create the underlying command.</param>
        public CommandInterpolator(int literalLength, int formattedCount, SqlCommandFactory factory, IDbConnection dbConnection)
        {
            if (factory == null)
            {
                throw new ArgumentNullException(nameof(factory));
            }

            if (dbConnection == null)
            {
                throw new ArgumentNullException(nameof(dbConnection));
            }

            interpolator = new SqlBuilderInterpolator(literalLength, formattedCount, dbConnection, factory.syntaxOptions);
        }

        /// <summary>
        /// Gets the command associated with the interpolated builder.
        /// </summary>
        public IDbCommand DbCommand => interpolator.DbCommand;

        /// <summary>
        /// Gets the syntax options applied by the interpolator.
        /// </summary>
        public SqlSyntaxOptions SyntaxOptions => interpolator.SyntaxOptions;

        /// <summary>
        /// Appends a literal piece of SQL to the internal buffer.
        /// </summary>
        /// <param name="s">The literal string to append.</param>
        public void AppendLiteral(string s) => interpolator.AppendLiteral(s);

        /// <summary>
        /// Adds a formatted value to the SQL query and ensures a parameter is created.
        /// </summary>
        /// <typeparam name="T">Type of the value to append.</typeparam>
        /// <param name="value">The value being interpolated.</param>
        /// <param name="name">Name of the argument being interpolated.</param>
        public void AppendFormatted<T>(T value, [CallerArgumentExpression(nameof(value))] string? name = null) => interpolator.AppendFormatted(value, name);

        /// <summary>
        /// Returns the built SQL query.
        /// </summary>
        /// <returns>The SQL string accumulated so far.</returns>
        public override string ToString() => interpolator.ToString();
    }
}

/// <summary>
/// Provides extension methods to build commands through <see cref="SqlCommandFactory"/> instances.
/// </summary>
public static class SqlCommandFactoryExtensions
{
    /// <summary>
    /// Creates a command using the configured syntax options and the provided interpolated SQL builder.
    /// </summary>
    /// <param name="factory">Factory supplying syntax options for the interpolator.</param>
    /// <param name="dbConnection">The connection used to create the command.</param>
    /// <param name="interpolator">Interpolator that builds the SQL and parameters.</param>
    /// <returns>A command initialized with text and parameters provided by <paramref name="interpolator"/>.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="factory"/> or <paramref name="dbConnection"/> is null.</exception>
    public static IDbCommand CreateCommand(this SqlCommandFactory factory, IDbConnection dbConnection, [InterpolatedStringHandlerArgument(nameof(factory), nameof(dbConnection))] SqlCommandFactory.CommandInterpolator interpolator)
    {
        if (factory == null)
        {
            throw new ArgumentNullException(nameof(factory));
        }

        if (dbConnection == null)
        {
            throw new ArgumentNullException(nameof(dbConnection));
        }

        return SqlCommandFactory.FinalizeCommand(interpolator);
    }

    /// <summary>
    /// Creates a command using the configured syntax options and the provided interpolated SQL builder.
    /// </summary>
    /// <param name="factory">Factory supplying syntax options for the interpolator.</param>
    /// <param name="dbConnection">The connection used to create the command.</param>
    /// <param name="interpolator">Interpolator that builds the SQL and parameters.</param>
    /// <returns>A command initialized with text and parameters provided by <paramref name="interpolator"/>.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="factory"/> or <paramref name="dbConnection"/> is null.</exception>
    public static DbCommand CreateCommand(this SqlCommandFactory factory, DbConnection dbConnection, [InterpolatedStringHandlerArgument(nameof(factory), nameof(dbConnection))] SqlCommandFactory.CommandInterpolator interpolator)
    {
        if (factory == null)
        {
            throw new ArgumentNullException(nameof(factory));
        }

        if (dbConnection == null)
        {
            throw new ArgumentNullException(nameof(dbConnection));
        }

        return (DbCommand)SqlCommandFactory.FinalizeCommand(interpolator);
    }
}
