//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Mathematics.Expressions {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Grammar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grammar() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Mathematics.Expressions.Grammar", typeof(Grammar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;g:Grammar xmlns:g=&quot;http://expression.mathematics.utils/Grammar.xsd&quot;&gt;
        ///  &lt;g:GroupMarkup open=&quot;(&quot; close=&quot;)&quot; /&gt;
        ///  &lt;g:GroupMarkup  open=&quot;[&quot; close=&quot;]&quot; /&gt;
        ///  &lt;g:GroupMarkup  open=&quot;{&quot; close=&quot;}&quot; /&gt;
        ///  &lt;g:Operand sign=&quot;=&quot; constructor=&quot;Assign&quot; /&gt;
        ///  &lt;g:Operand sign=&quot;+&quot; constructor=&quot;Add&quot; /&gt;
        ///  &lt;g:Operand sign=&quot;-&quot; constructor=&quot;Subtract&quot; /&gt;
        ///  &lt;g:Operand sign=&quot;*&quot; constructor=&quot;Multiply&quot; /&gt;
        ///  &lt;g:Operand sign=&quot;/&quot; constructor=&quot;Divide&quot; /&gt;
        ///  &lt;g:Operand sign=&quot;^&quot; constructor=&quot;Power&quot;  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SimpleGrammar {
            get {
                return ResourceManager.GetString("SimpleGrammar", resourceCulture);
            }
        }
    }
}
