using System;
using System.Reflection;
using System.Runtime.InteropServices;

using Microsoft.VisualStudio.TestTools.UnitTesting;

using Utils.Reflection;
using Utils.Reflection.Reflection.Emit;

namespace UtilsTest.Reflection;

/// <summary>
/// Validates <see cref="EmitWorkerRoundRobinProxy"/> can be generated by
/// <see cref="DispatchProxy.Create{TInterface, TProxy}"/> and its behavior before any worker is
/// attached, and <see cref="LibraryMapper.EmitRoundRobin{TInterface}"/>'s upfront argument validation —
/// without starting a real isolated worker process (spawning several is out of scope for automated
/// tests here, same accepted limitation as <c>EmitWorkerProxyTests</c>).
/// </summary>
[TestClass]
public class EmitWorkerRoundRobinProxyTests
{
    public interface ITinyInterface : IDisposable
    {
        int Foo(int value);
    }

    [TestMethod]
    public void DispatchProxy_Create_ProducesAWorkingProxyInstance()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerRoundRobinProxy>();

        Assert.IsNotNull(proxy);
        Assert.IsInstanceOfType(proxy, typeof(EmitWorkerRoundRobinProxy));
    }

    [TestMethod]
    public void Invoke_BeforeWorkersAreAttached_ThrowsObjectDisposedException()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerRoundRobinProxy>();

        Assert.ThrowsException<ObjectDisposedException>(() => proxy.Foo(1));
    }

    [TestMethod]
    public void Dispose_BeforeWorkersAreAttached_DoesNotThrow()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerRoundRobinProxy>();

        proxy.Dispose();
    }

    [TestMethod]
    public void EmitRoundRobin_WithZeroWorkers_ThrowsArgumentOutOfRangeException()
    {
        Assert.ThrowsException<ArgumentOutOfRangeException>(
            () => LibraryMapper.EmitRoundRobin<ITinyInterface>("does-not-matter.dll", CallingConvention.Winapi, workerCount: 0));
    }

    [TestMethod]
    public void EmitRoundRobin_WithNegativeWorkerCount_ThrowsArgumentOutOfRangeException()
    {
        Assert.ThrowsException<ArgumentOutOfRangeException>(
            () => LibraryMapper.EmitRoundRobin<ITinyInterface>("does-not-matter.dll", CallingConvention.Winapi, workerCount: -1));
    }
}
