using System;
using System.Reflection;

using Microsoft.VisualStudio.TestTools.UnitTesting;

using Utils.Reflection.Reflection.Emit;

namespace UtilsTest.Reflection;

/// <summary>
/// Validates that <see cref="EmitWorkerProxy"/> can actually be generated by
/// <see cref="DispatchProxy.Create{TInterface, TProxy}"/> and that <c>Dispose</c> is intercepted
/// before a worker is attached — without starting a real isolated worker process.
/// </summary>
[TestClass]
public class EmitWorkerProxyTests
{
    public interface ITinyInterface : IDisposable
    {
        int Foo(int value);
    }

    [TestMethod]
    public void DispatchProxy_Create_ProducesAWorkingProxyInstance()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();

        Assert.IsNotNull(proxy);
        Assert.IsInstanceOfType(proxy, typeof(EmitWorkerProxy));
    }

    [TestMethod]
    public void Invoke_BeforeWorkerIsAttached_ThrowsObjectDisposedException()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();

        Assert.ThrowsException<ObjectDisposedException>(() => proxy.Foo(1));
    }

    [TestMethod]
    public void Dispose_BeforeWorkerIsAttached_DoesNotThrow()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();

        // Dispose is special-cased in EmitWorkerProxy.Invoke and must be a safe no-op when no
        // worker was ever attached (for example if construction failed before AttachWorker ran).
        proxy.Dispose();
    }

    // ─── Item 49: invocation lease prevents concurrent disposal ──────────────────

    [TestMethod]
    public void Invoke_AfterDispose_ThrowsObjectDisposedException()
    {
        // Verify that after Dispose the read lock is immediately available but worker is null,
        // so subsequent calls throw ObjectDisposedException rather than silently using a dead worker.
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();
        proxy.Dispose();

        Assert.ThrowsException<ObjectDisposedException>(() => proxy.Foo(1));
    }

    [TestMethod]
    public void Dispose_CalledTwice_DoesNotThrow()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();
        proxy.Dispose();
        proxy.Dispose(); // Must be idempotent.
    }

    // ─── Item 14: synchronization gate replaced (no ReaderWriterLockSlim) ────────

    [TestMethod]
    public void Dispose_AfterConcurrentInvocationAttempt_DoesNotDeadlock()
    {
        // Verify that the active-call counting mechanism does not deadlock when concurrent
        // invocations and a dispose race. Since we have no worker attached, invocations throw
        // ObjectDisposedException, but the finally block must always decrement the counter.
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();

        // Fire-and-forget: invoke on a background thread; it will throw ObjectDisposedException
        // because no worker is attached, but must still release the active-call count.
        var invokeThread = new System.Threading.Thread(() =>
        {
            try { proxy.Foo(1); }
            catch (ObjectDisposedException) { /* expected */ }
        });
        invokeThread.Start();
        invokeThread.Join(System.TimeSpan.FromSeconds(2));

        // Dispose must succeed without deadlocking, even after the concurrent attempt.
        proxy.Dispose();
    }

    [TestMethod]
    public void Invoke_AfterDispose_ThrowsImmediately()
    {
        ITinyInterface proxy = DispatchProxy.Create<ITinyInterface, EmitWorkerProxy>();
        proxy.Dispose();

        // The fast-path check (disposeState != 0) must fire before entering the active-call region.
        var ex = Assert.ThrowsException<ObjectDisposedException>(() => proxy.Foo(42));
        Assert.IsNotNull(ex);
    }
}
