name: Utils

on:
    pull_request:
        branches:
            - '**'

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: ['9.0.x']

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET ${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}
            - name: Build
              run: dotnet build --configuration GitHub
            - name: Scan vulnerable packages
              run: dotnet list Utils.sln package --vulnerable --include-transitive
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-outputs-${{ github.ref_name }}
                  path: |
                      **/bin/GitHub/**
                  if-no-files-found: warn

    test:

        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - test-suite: unit
                      project: UtilsTest/UtilsTest.Unit.csproj
                    - test-suite: functional
                      project: UtilsTest.Functional/UtilsTest.Functional.csproj
        name: Test (${{ matrix.test-suite }})

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET 9.0.x
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '9.0.x'
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build-outputs-${{ github.ref_name }}
            - name: Restore packages
              run: dotnet restore ${{ matrix.project }}
            - name: Test (${{ matrix.test-suite }})
              run: dotnet test ${{ matrix.project }} --no-build --configuration GitHub --verbosity normal
