// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UtilsTest.Unit.Mathematics.LinearAlgebra
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class MatrixTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Mathematics/LinearAlgebra", "MatrixTests", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "MatrixTests.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Mathematics/LinearAlgebra/MatrixTests.feature.ndjson", 8);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 5, DisplayName="Matrix Additions")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Matrix Additions")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MatrixTests")]
        public async global::System.Threading.Tasks.Task MatrixAdditions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix Additions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table4.AddRow(new string[] {
                            "1",
                            "2"});
                table4.AddRow(new string[] {
                            "3",
                            "4"});
#line 6
 await testRunner.GivenAsync("m1 is a matrix", ((string)(null)), table4, "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table5.AddRow(new string[] {
                            "5",
                            "6"});
                table5.AddRow(new string[] {
                            "7",
                            "8"});
#line 10
   await testRunner.AndAsync("m2 is a matrix", ((string)(null)), table5, "And ");
#line hidden
#line 14
 await testRunner.WhenAsync("I compute matrix m3 = m1 + m2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
 await testRunner.WhenAsync("I compute matrix m4 = m2 + m1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table6.AddRow(new string[] {
                            "6",
                            "8"});
                table6.AddRow(new string[] {
                            "10",
                            "12"});
#line 16
 await testRunner.ThenAsync("I expect matrix m3 equals", ((string)(null)), table6, "Then ");
#line hidden
#line 20
    await testRunner.AndAsync("I expect m3 = m4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.AndAsync("det(m1) = -2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync("det(m2) = -2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("det(m3) = -8", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 25, DisplayName="Matrix Multiplications")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Matrix Multiplications")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MatrixTests")]
        public async global::System.Threading.Tasks.Task MatrixMultiplications()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix Multiplications", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table7.AddRow(new string[] {
                            "1",
                            "2"});
                table7.AddRow(new string[] {
                            "3",
                            "4"});
#line 26
 await testRunner.GivenAsync("m1 is a matrix", ((string)(null)), table7, "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table8.AddRow(new string[] {
                            "5",
                            "6"});
                table8.AddRow(new string[] {
                            "7",
                            "8"});
#line 30
   await testRunner.AndAsync("m2 is a matrix", ((string)(null)), table8, "And ");
#line hidden
#line 34
 await testRunner.WhenAsync("I compute matrix m = m1 * m2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table9.AddRow(new string[] {
                            "19",
                            "22"});
                table9.AddRow(new string[] {
                            "43",
                            "50"});
#line 35
 await testRunner.ThenAsync("I expect matrix m equals", ((string)(null)), table9, "Then ");
#line hidden
#line 39
 await testRunner.AndAsync("det(m) = 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.WhenAsync("I compute matrix m = m2 * m1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table10.AddRow(new string[] {
                            "23",
                            "34"});
                table10.AddRow(new string[] {
                            "31",
                            "46"});
#line 41
 await testRunner.ThenAsync("I expect matrix m equals", ((string)(null)), table10, "Then ");
#line hidden
#line 45
 await testRunner.AndAsync("det(m) = 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 47, DisplayName="Vector mulitplication")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Vector mulitplication")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MatrixTests")]
        public async global::System.Threading.Tasks.Task VectorMulitplication()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Vector mulitplication", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2"});
                table11.AddRow(new string[] {
                            "1",
                            "2"});
                table11.AddRow(new string[] {
                            "3",
                            "4"});
#line 48
 await testRunner.GivenAsync("m1 is a matrix", ((string)(null)), table11, "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "v1",
                            "vr"});
                table12.AddRow(new string[] {
                            "5",
                            "19"});
                table12.AddRow(new string[] {
                            "7",
                            "43"});
#line 52
 await testRunner.AndAsync("Given these vectors", ((string)(null)), table12, "And ");
#line hidden
#line 56
 await testRunner.WhenAsync("I compute vector vt = m1 * v1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
 await testRunner.ThenAsync("I expect vr = vt", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 60, DisplayName="Matrix determinant 3*3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Matrix determinant 3*3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MatrixTests")]
        public async global::System.Threading.Tasks.Task MatrixDeterminant33()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix determinant 3*3", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2",
                            "C3"});
                table13.AddRow(new string[] {
                            "12",
                            "10",
                            "9"});
                table13.AddRow(new string[] {
                            "2",
                            "8",
                            "6"});
                table13.AddRow(new string[] {
                            "1",
                            "13",
                            "14"});
#line 61
 await testRunner.GivenAsync("m is a matrix", ((string)(null)), table13, "Given ");
#line hidden
#line 66
 await testRunner.ThenAsync("det(m) = 350", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 68, DisplayName="Matrix determinant 4*4")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Matrix determinant 4*4")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MatrixTests")]
        public async global::System.Threading.Tasks.Task MatrixDeterminant44()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix determinant 4*4", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2",
                            "C3",
                            "C4"});
                table14.AddRow(new string[] {
                            "12",
                            "10",
                            "9",
                            "-12"});
                table14.AddRow(new string[] {
                            "2",
                            "-8",
                            "6",
                            "4"});
                table14.AddRow(new string[] {
                            "1",
                            "-13",
                            "14",
                            "2"});
                table14.AddRow(new string[] {
                            "1",
                            "8",
                            "-6",
                            "7"});
#line 69
 await testRunner.GivenAsync("m is a matrix", ((string)(null)), table14, "Given ");
#line hidden
#line 75
 await testRunner.ThenAsync("det(m) = -7622", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 77, DisplayName="Matrix determinant 5*5")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Matrix determinant 5*5")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "MatrixTests")]
        public async global::System.Threading.Tasks.Task MatrixDeterminant55()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matrix determinant 5*5", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "C1",
                            "C2",
                            "C3",
                            "C4",
                            "C5"});
                table15.AddRow(new string[] {
                            "12",
                            "10",
                            "9",
                            "-12",
                            "2"});
                table15.AddRow(new string[] {
                            "2",
                            "-8",
                            "6",
                            "4",
                            "-4"});
                table15.AddRow(new string[] {
                            "1",
                            "-13",
                            "14",
                            "2",
                            "4"});
                table15.AddRow(new string[] {
                            "1",
                            "8",
                            "-6",
                            "7",
                            "4"});
                table15.AddRow(new string[] {
                            "-1",
                            "-2",
                            "7",
                            "14",
                            "-18"});
#line 78
 await testRunner.GivenAsync("m is a matrix", ((string)(null)), table15, "Given ");
#line hidden
#line 85
 await testRunner.ThenAsync("det(m) = 294064", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
